/* ============================================
   仙途·轮回诀 — 多语言（中文 / English 切换）
   设计原则：
   - 所有 UI 文案与【数据译名】集中在本文件，游戏逻辑文件（config/ui/main/...）不改动数据。
   - 数据译名按「中文原串」查表（I18N.DATA），故无需改动 config.js 等数据文件，零回归风险。
   - 切换语言后派发 'langchange' 事件 + 调用 UI.refreshAll()（若存在）重渲染当前面板。
   ============================================ */
const I18N = {
    /* UI 文案：T(key, fallback) 查表；英文缺失时回退 fallback（默认即中文原串） */
    en: {
  // —— 设置面板 ——,
  'settings': 'Settings',
  'autoSave': 'Auto Save',
  'anim': 'Battle Animation',
  'sound': 'Sound Effects',
  'manualSave': 'Save Now',
  'slotSelect': 'Ascend · Switch Save',
  'reset': 'Reset Game',
  'close': 'Close',
  'language': 'Language',
  // —— 顶部资源栏 tooltips ——,
  'res.zhanli': 'Power',
  'res.stone': 'Spirit Stones',
  'res.ling': 'Spirit Energy',
  'res.life': 'Lifespan (Seclusion cap)',
  // —— 侧边导航 ——,
  'panel.cultivate': 'Cultivation',
  'panel.combat': 'Combat',
  'panel.explore': 'Exploration',
  'panel.inventory': 'Inventory',
  'panel.skill': 'Divine Arts',
  'panel.shop': 'Market',
  'panel.quest': 'Quests',
  'panel.mainstory': 'Story',
  'panel.friends': 'Companions',
  'panel.reincarnate': 'Reincarnation',
  'panel.xianlu': 'Immortal Path',
  'panel.realm': 'Realms',
  // —— 修炼区 ——,
  'breakthrough': 'Breakthrough',
  'seclude': 'Seclude',
  'enlighten': 'Enlighten',
  'layer': 'Layer',
  'duanLabel': 'Layer',
  // —— 境界图鉴表头 ——,
  'realmHeader': 'Realm',
  'baseHeader': 'Base Power',
  'costHeader': 'Full-Layer Breakthrough Cost',
  'needRealmReq': 'Requires {x} Realm',
  'notReached': 'Not Reached',
  'unlockAfter': 'Unlock after reaching {x} Realm.',
  'currentRealm': 'Current Realm:',
  'chaptersUnlocked': 'chapters unlocked',
  'prologue': 'Prologue',
  'final': 'Final',
  'reqRealmMax': 'Required Realm (Max Layer)',
  'capHeader': 'Power Cap',
  // —— 通用 toast ——,
  'toast.noLing': 'Insufficient Spirit Energy',
  'toast.noRealm': 'Realm too low to challenge this enemy',
  'toast.skillCd': 'Skill on cooldown',
  'toast.treasureCd': 'Treasure on cooldown',
  'toast.saved': 'Saved',
  'toast.reset': 'Game reset',
  'combat.activateFabao': 'Activate Treasure',
  'combat.attack2': 'Attack',
  'combat.avatarXian': 'Immortal',
  'combat.comboHit': '(Combo)',
  'combat.defeat': 'Victory',
  'combat.elemCtr': '(Element Counter)',
  'combat.gain': ', Gained',
  'combat.lose': 'You were defeated...',
  'combat.reflect': 'Reflect',
  'combat.sealed': 'Sealed, unable to act',
  'combat.stone': 'Spirit Stone',
  'combat.zhanli': 'Power',
  'cult.breakTo': 'Breakthrough to',
  'cult.daoxin': 'Dao Heart Clarity, break through to',
  'cult.exchangeMid': 'Power, exchanged for',
  'cult.hardFailMid': 'Failed! Realm drops, lost',
  'cult.hpAtkMid': ' · ATK ×',
  'cult.layerUnit': 'Layer',
  'cult.lingResolve': 'Resolve with Spirit Stones',
  'cult.maxRealm': 'Reached highest Realm, cannot break through!',
  'cult.paused': 'Cultivation paused',
  'cult.pillLogPre': 'After',
  'cult.rateGetMid': '%, Spirit Stone gain +',
  'cult.rebirthCapPre': 'Reached Reincarnation limit ',
  'cult.sangong': 'Disperse cultivation, restart (Round ',
  'cult.shiPill': ' Lifetimes! Foundation greatly improved: HP ×',
  'cult.talentAwaken': 'Realm breakthrough, awakened Talent points +3! Go to the Talent panel to learn',
  'cult.year': 'Year',
  'cult.youliEnd': 'Travel',
  'cult.zhanliImprove': 'Power improved, break through to',
  'cult.zhanliUnit': 'Power',
  'expl.auctionItem': 'Auction Item:',
  'expl.beggarLeave': 'Sent them off, at peace',
  'expl.bid': 'Bid',
  'expl.buyOk': 'Purchase successful',
  'expl.claimReward2': ', Claim Reward',
  'expl.dragonPearl': 'Dragon King gifts you Spirit Pearl ×2',
  'expl.gain': 'Gained',
  'expl.goodKarma': 'Good is rewarded, gained',
  'expl.hurtLog': 'Accidentally injured, lost',
  'expl.needRest': 'Need rest before exploring again (about',
  'expl.nothing': 'Nothing happened',
  'expl.questNotDone': 'Quest not completed',
  'expl.robLog': 'Plundered others, gained',
  'expl.stone': 'Spirit Stone',
  'friend.badCode': 'Invalid Immortal Path share code',
  'friend.noStoneGift': 'Not enough Spirit Stones, cannot gift',
  'friend.unknownType': 'Unknown share code type',
  'inv.alchemyOk': 'Alchemy successful:',
  'inv.buffAtk': 'ATK + during combat',
  'inv.changeGf': 'Switch Technique to ',
  'inv.enhMax': 'Reached enhancement cap +100!',
  'inv.equipGf': 'Equipped Technique:',
  'inv.forge': 'Forge',
  'inv.gfOwned': 'Already own this Technique',
  'inv.learnSkillLog': 'Learned Divine Ability ',
  'inv.noGf': 'Have not learned this Technique',
  'inv.paren': '(',
  'inv.permAtk': 'Permanent ATK +',
  'inv.permLing': 'Permanent Spirit Energy +',
  'inv.realmLowPet': 'Realm insufficient, cannot subdue',
  'inv.skillMax': 'Skill at max level',
  'inv.turnsEnd': 'Turns)',
  'inv.upTo': 'Raised to',
  'main.av.mo': 'Demon',
  'main.confirmDel': 'Confirm delete ',
  'main.dayAgo': 'days ago',
  'main.deleted': 'Deleted this Dao Path',
  'main.loadFail': 'Failed to load save',
  'main.cultivated': 'cultivated',
  'main.loaded': 'Game loaded',
  'main.elem.metal': 'Metal Spirit Root',
  'main.exclaim': '!',
  'main.justNow': 'Just now',
  'main.lifeEndBody2': 'A fleeting dream of the mortal world, immortal ties now severed. This cultivation path returns to Reincarnation—choose a new fate and tread the Immortal Path once more.',
  'main.noName': 'Nameless Cultivator',
  'main.resetTitle': '⚠️ Reset Game',
  'main.saveUnavailBody': '<p>Current browser <b>has blocked local storage</b>. The most common cause: you opened it via <code>file://</code> by double-clicking <code>index.html</code>.</p><p style="margin-top:10px">This means all progress <b>cannot be saved</b> and will be lost on refresh or close — i.e. "saving does nothing".</p><p style="margin-top:12px">✅ <b>Solution (pick any one)</b>:</p><p style="margin-top:6px">① Open via <code>http://</code>: run <code>python -m http.server 8080</code> in the game folder, then visit <code>http://localhost:8080</code>.</p>',
  'main.tempSave': 'Temporarily saved to session (valid until you close the tab). We recommend opening the game via http:// for permanent saving.',
  'main.tip4': 'Purple energy from the east, all things made new...',
  'main.yrAgo': 'years ago',
  'save.exportFail': 'Export failed:',
  'save.resetFail': 'Reset failed:',
  'save.unnamed': 'Nameless Cultivator',
  'shop.noStone': 'Not enough Spirit Stones, need',
  'shop.spend': 'Spend',
  'ui.allExchange': 'All exchangeable',
  'ui.av.fo': 'Buddha',
  'ui.avatarUp': 'Avatar #',
  'ui.benMingFaBao': '⚔ Natal Treasure',
  'ui.buy': 'Buy',
  'ui.buyPetFood': 'Buy Spirit Beast Feed',
  'ui.capDiff': 'Still need <b class=',
  'ui.chengQuDongTian': ' × Cave Heaven ×',
  'ui.claimReward': 'Claim Reward',
  'ui.codeCopied': 'Profile code copied, send to friends',
  'ui.confirmPillRb': 'Confirm using Reincarnation Pill to reincarnate?',
  'ui.continueCult': 'Continue Cultivation',
  'ui.count': 'Quantity:',
  'ui.cultPause': 'Cultivation paused',
  'ui.decompose': 'Decompose',
  'ui.effect': 'Effect:',
  'ui.enhance': 'Enhance',
  'ui.equip': 'Equip',
  'ui.evolveFail': 'Transformation failed',
  'ui.exPlaceholder': 'Enter the Power amount to exchange',
  'ui.exTier4': '100 million Power',
  'ui.exchangeOkMid': ', gained',
  'ui.faZe': '📜 Law Comprehension',
  'ui.feedOk': 'Feeding successful, Spirit Beast EXP +',
  'ui.foe': 'Opponent',
  'ui.formUp': ' form, attributes greatly increased',
  'ui.giftCodeCopied': 'Gift code copied',
  'ui.go': 'Go',
  'ui.hold': '(Holding',
  'ui.importFail': 'Import failed',
  'ui.layer': 'Layer',
  'ui.level': 'Level:',
  'ui.ling2': 'Spirit',
  'ui.lingShiBonus': ' Spirit Stone +',
  'ui.lingShiUnit': ' Spirit Stone',
  'ui.material': 'Material',
  'ui.multiplier': 'Multiplier:',
  'ui.newChapter': '✦ New Chapter Available',
  'ui.nianResult': 'Year · Harvest',
  'ui.noLife': 'No lifespan available',
  'ui.noSell': 'No items to sell',
  'ui.notLearned': 'Not learned',
  'ui.offlineTitle': 'Offline Cultivation',
  'ui.parenClose': ')',
  'ui.petDetailHint': 'Select a Spirit Beast to view details',
  'ui.pillFurnace': '🔥 Pill Furnace · Alchemy (Materials + Spirit Stones, with a chance of great success doubling the yield)',
  'ui.powerLack': 'Not enough Power, still need',
  'ui.quality': 'Quality:',
  'ui.rbClose': '</b>',
  'ui.realmCurLayer': ' Layer (Total ',
  'ui.realmModuleUnloaded': 'Realm Codex module not loaded, please press <b>Ctrl+Shift+R</b> to hard refresh the page',
  'ui.rebirthCol': 'Lifetimes',
  'ui.resistRate': 'Hard-Resist Success Rate:',
  'ui.round': 'Round',
  'ui.seclS2': 'Minor Achievement',
  'ui.seclS6': 'A thousand years have passed',
  'ui.sell': 'Sell',
  'ui.setMainPet': 'Set as main Spirit Beast',
  'ui.shengZhi2': ' Raised to Lv.',
  'ui.slideRight': 'Slide right',
  'ui.slotWeapon': 'Weapon',
  'ui.stoneLack': 'Spirit Stones insufficient',
  'ui.tapMaxed': "Reached this life's limit",
  'ui.thLevel': 'Level',
  'ui.thOutput': 'Output',
  'ui.trainFail': 'Cultivation failed',
  'ui.tribDescend': ' Descends!',
  'ui.tribTip': 'Successful Tribulation grants Aftermath Charm permanent bonus; failure causes Realm to fall and Power to be damaged.',
  'ui.tut1.title': 'Step onto the Immortal Path',
  'ui.tut11.title': 'Divine Ability',
  'ui.tut13.title': 'Reincarnation',
  'ui.tut15.title': 'Talent',
  'ui.tut17.title': 'Immortal Path (Great Dao +)',
  'ui.tut19.title': 'The Endless Dao Path',
  'ui.tut3.title': 'Seclusion · Travel · Exchange',
  'ui.tut5.title': 'Epiphany · Insight',
  'ui.tut7.title': 'Combat to Prove the Dao',
  'ui.tut9.title': 'Market Treasure Hunt',
  'ui.unlockChapter': 'Unlocks this chapter after reaching the Realm.',
  'ui.use': 'Use',
  'ui.xianluLocked': 'Immortal Path Locked',
  'ui.xiuEff': 'Cultivation Efficiency +',
  'ui.youliBody1': 'Travel far and wide, seek treasures and meet immortals. <b>Each year of travel costs one year of lifespan</b>, yet you may obtain <b>Spirit Stones</b>, <b>Materials</b>, even <b>Pills</b> and <b>Adventures</b>. Current lifespan:',
  'ui.youliResultBody': 'Traveled the four corners, gains as follows:',
  'ui.youliS4': 'Visited Every Cave Heaven',
  'ui.youliY1': 'One Year',
  'ui.youliY5': 'Thousand Years',
  'ui.zhu': ' plants',
  'combat.affBy': 'by',
  'combat.avatarDao': 'Dao',
  'combat.cast': 'casts',
  'combat.comma': ',',
  'combat.defeatedLoss': 'Defeated, lost',
  'combat.escapeOk': 'Escaped successfully',
  'combat.gainShield': ', gained',
  'combat.lost': ', lost',
  'combat.reflectDmg': ', reflected damage',
  'combat.shieldAbsorb': 'Shield absorbed',
  'combat.strong': 'Powerful',
  'cult.breakFail': 'Breakthrough failed! Qi deviation!',
  'cult.chooseSeclude': 'Choose seclusion duration',
  'cult.enlightenLack': 'Insufficient resources to attain enlightenment',
  'cult.exchangePre': 'for',
  'cult.hardFailPre': 'Endure',
  'cult.inputZhanli': 'Enter the amount of Power to exchange',
  'cult.lifeAdd': 'Lifespan +',
  'cult.lingStone': 'Spirit Stones',
  'cult.needHerbPre': 'Requires ',
  'cult.pctEnd': '%)',
  'cult.protectLack': 'Not enough Spirit Stones to ask a Guardian to avert the Heavenly Tribulation',
  'cult.rateMid': '%, cultivation rate +',
  'cult.reincarnateFreePre': 'Free reincarnation to the ',
  'cult.secludePre': 'Seclusion',
  'cult.shopSale': '(available in the market)',
  'cult.useBreakPill': 'Use Barrier-Breaking Pill, success rate +20%',
  'cult.yearEnd': 'years)',
  'cult.youliPre': 'Travel',
  'cult.zhanliLack2': 'Insufficient Power',
  'cult.zhong': 'fold, Power + per session',
  'expl.auctionTitle': 'Auction Event',
  'expl.beggarPill': 'A beggar gives you 2 Foundation Pills',
  'expl.bidLog': 'Auction won: ',
  'expl.catchPet': 'Captured Spirit Beast:',
  'expl.completeLog': 'Quest completed: ',
  'expl.enter': 'Enter',
  'expl.gainItem': 'Obtained:',
  'expl.goodKarmaLog': 'Good deeds bring blessings',
  'expl.leave': 'Leave',
  'expl.newQuest': 'Received a new sect quest',
  'expl.oldSmile': 'The old man smiles mysteriously and produces three items:',
  'expl.questPreLog': 'Received a sect quest, prepaid ',
  'expl.robStone': 'Looted ',
  'expl.stoneSpace': 'Spirit Stones ',
  'friend.badContent': 'Invalid share code content',
  'friend.pickGift': 'Please select Spirit Stones or items to gift first',
  'inv.alchemyBig': 'Alchemy great success!',
  'inv.bracket': '[',
  'inv.buffDef': 'Defense + in combat',
  'inv.decompGain': 'Obtained from dismantling',
  'inv.enhOk': 'Enhancement success! +',
  'inv.equipLog': 'Equipped ',
  'inv.forgeLog': 'Forged at the furnace ',
  'inv.hpBattle': 'HP (active in battle)',
  'inv.level': 'Lv',
  'inv.noGfEquipped': 'No Technique currently equipped',
  'inv.parenEnd': ')',
  'inv.permCrit': 'Permanent crit rate +',
  'inv.permSpd': 'Permanent speed +',
  'inv.restoreHp': 'Restored',
  'inv.success': 'Success',
  'inv.unequipGf': 'Technique unequipped:',
  'inv.use': 'Use',
  'main.av.xian': 'Immortal',
  'main.confirmDelBtn': 'Confirm Delete',
  'main.delSave': 'Delete Save',
  'main.dot': '.',
  'main.elem.water': 'Water Spirit Root',
  'main.gotIt': 'Got it',
  'main.layer': 'Layer',
  'main.minAgo': 'minutes ago',
  'main.opIrrev': 'This operation',
  'main.saveFail': 'Save failed: the browser blocks local storage (usually caused by opening via file://). Please open via http://',
  'main.selItem': 'Select an item to view details',
  'main.tip1': 'Focus your spirit and begin the immortal path...',
  'main.tip5': 'The supreme is emotionless; the great dao is simple...',
  'main.yuhua': 'Ascend to the Void',
  'save.loadFail': 'Load failed:',
  'save.saveFail': 'Save failed:',
  'shop.buyLog': 'Market purchase ',
  'shop.owned': 'Owned',
  'ui.accept': 'Accept',
  'ui.atk': 'Attack:',
  'ui.av.mo': 'Demon',
  'ui.back': 'Back',
  'ui.benMingFaBaoShengZhi': 'Life-bound Treasure upgraded to',
  'ui.buyEvoPill': 'Buy Transformation Pill',
  'ui.cancel': 'Cancel',
  'ui.capDiffEnd': '</b> to reincarnate for free',
  'ui.chengQuFaBao': ' × Treasure ×',
  'ui.claimed': ' · Reward claimed',
  'ui.combo': 'Combo',
  'ui.confirmSell': 'Confirm Sale',
  'ui.continueXian': 'Continue the Immortal Path',
  'ui.craft': 'Craft',
  'ui.cultivating': 'Qi flows; Power grows slowly',
  'ui.def': 'Defense:',
  'ui.elemDmg': 'attribute, damage +50%',
  'ui.enlightenTip': 'Spend either one to gain one level of enlightenment.',
  'ui.equipTab': 'Equipment',
  'ui.evolveLog': 'Spirit Beast transformation advanced, aptitude transformed',
  'ui.exTier1': '100k Power',
  'ui.exTier5': '1B Power',
  'ui.exchangeTitle': 'Exchange Spirit Stones',
  'ui.fabaoDot': 'Treasure·',
  'ui.fenShen': '🪞 Clone Avatar',
  'ui.foeTurn': '☯ Enemy Turn…',
  'ui.freeRbBody': 'Dissolve cultivation and rebuild: Realm, <b>Power</b>, gear, and lifespan reset to zero; re-tread the immortal path from scratch. Yet your permanent HP/Attack bonuses, cultivation gains, enlightenment, and post-tribulation echoes are all retained—relying on your remaining foundation to reclaim the path faster.',
  'ui.giftCodeGen': 'Gift code generated. Send to a friend to deliver (already deducted from you).',
  'ui.guardian': 'Invite Guardian',
  'ui.hour': 'hours',
  'ui.intimacy': 'Intimacy ',
  'ui.learn': 'Learn',
  'ui.life': 'Lifespan:',
  'ui.lingCost': 'Spirit Energy Cost:',
  'ui.lingShiBuy': 'Spirit Stones, purchasable directly below). You currently have <b>',
  'ui.locked': '🔒 Locked (requires ',
  'ui.maxed': 'Maxed',
  'ui.need': 'Requires',
  'ui.nextLife': 'Next life (the ',
  'ui.noAvatar': 'No avatar created yet',
  'ui.noMainStory': 'No main story yet.',
  'ui.noZhanli': 'No Power available',
  'ui.offlineBody': 'Fellow Cultivator offline cultivation',
  'ui.ok': 'Confirm',
  'ui.pasteCode': 'Please paste the share code first',
  'ui.petEmptyTip': 'No Spirit Beast captured yet. Go to <b>Market·Spirit Beasts</b> to buy, or capture a young dragon at <b>Exploration·East Sea Dragon Palace</b>.',
  'ui.pillRbBody': 'Will consume ',
  'ui.powerPlus': 'Power +',
  'ui.rate': 'Rate',
  'ui.read': '✓ Read',
  'ui.realmCurMid': '</b> level ',
  'ui.realmParen': 'Realm)',
  'ui.recv': 'Received ',
  'ui.resistTrib': 'Endure the Heavenly Tribulation',
  'ui.rparen': ')',
  'ui.seclS3': 'Seclude half a lifetime',
  'ui.secludeMid': ', realized ',
  'ui.sellBody': 'Are you sure you want to sell this equipment?',
  'ui.shengJi': 'Upgrade (',
  'ui.shi': ' life',
  'ui.slotAcc': 'Accessory',
  'ui.spd': 'Speed:',
  'ui.summonMainPet': 'Summon main battle Spirit Beast',
  'ui.thCave': 'Grotto-Heaven',
  'ui.thMult': 'Multiplier',
  'ui.thTier': 'Tier',
  'ui.trainOk': 'Spirit Beast training complete, ',
  'ui.tribHurt': '💥 Dao Foundation Damaged',
  'ui.tribTitle': '⚡ Heavenly Tribulation Descends',
  'ui.tut10.body': 'The <b>Qiankun Pouch</b> stores gear and pills at your side. Equipping <b>Weapon·Armor·Accessory·Treasure</b> boosts HP, Attack, Defense, and Spirit Energy; pills provide temporary benefits. Your Power largely depends on this.',
  'ui.tut12.body': "Befriend fellow cultivators via <b>Profile Code</b>; the <b>Fellow Cultivator Ranking</b> sorts by Power for mutual competition. You may also spar and discuss the Dao with fellow cultivators to verify each other's cultivation.",
  'ui.tut14.body': 'Your <b>Spirit Beast</b> lives and dies with you. Buy Spirit Beasts at the market or capture young dragons at the East Sea Dragon Palace. In the <b>Cultivation·Spirit Beast</b> subtab, select a beast to <b>Feed</b> (uses beast feed), <b>Cultivate</b> (uses Power), or <b>Transform</b> (uses Transformation Pill). Higher level and transformation mean stronger attributes and fiercer battles.',
  'ui.tut16.body': 'The cultivation path comprises <b>103 major realms × 15 layers</b>: from Qi Refining all the way to <b>Dao Ancestor</b>; beyond the Dao Ancestor lie transcendent realms like <b>Dao Lord → Dao Venerable → Dao Sage → … → Taiyi → … → Tailiao</b>, each closer to the source of the Great Dao. ※ Beyond Dao Ancestor, stage difficulty (breakthrough Power/Spirit Stone thresholds, duel enemy strength) is uniformly <b>×900</b>, requiring vast Power to reach the summit. Upon reaching <b>Mahayana (Great Completion)</b> and above, all manner of <b>ultimate arts and treasures</b> appear in the world—the market unlocks immortal treasures like <b>Taiqing Pagoda · Zhutian Cauldron · Wuheng Mirror</b>, divine powers reveal ultimate arts like <b>Taiqing Sword Art → Dao · Supreme</b>, Spirit Beasts gain <b>Qilin King · Primordial Ancestral Dragon</b>, and you may ascend to <b>Nine Heavens · Zhutian Battlefield</b> to seize fortune in extremis.',
  'ui.tut18.body': 'Click the <b>Realm</b> icon in the sidebar to open the <b>Realm Codex</b> panel, where you can overview <b>all 103 major realms</b> (base Power per layer and full-layer breakthrough cost) and the <b>Power cap per reincarnation</b> (free-reincarnation threshold, current-life Power growth cap). The caps corresponding to your current realm and current life cycle are <b>highlighted with a gold background</b>, letting you see at a glance how far you are from the next life.',
  'ui.tut2.body': '<b>Power</b> is the foundation of cultivation. Click Cultivate (click to gather qi) to manually accumulate Power; it also slowly grows on its own—the Qi at the top is your Power.',
  'ui.tut4.body': 'When Power is full, click <b>Breakthrough</b> to advance your realm, gain lifespan, and strengthen foundation. Each <b>major realm breakthrough</b> triggers a <b>Heavenly Tribulation</b> (ask a Guardian to avert it or endure it; success grants permanent cultivation and Spirit Stone bonuses) and <b>awakens talent points</b>. ※ Beyond the <b>Dao Ancestor</b>, the transcendent line (Dao Lord → Great Dao, 20 realms total) requires a <b>×30</b> surge in breakthrough Power—accumulate early.',
  'ui.tut6.body': 'Watch the <b>Lifespan</b> at the top right: it drops by one every real <b>minute</b>, and seclusion or travel also consumes lifespan. When lifespan runs out you <b>ascend to the void</b>, so cultivate without delay.',
  'ui.tut8.body': '<b>Exploration</b> lets you visit famed mountains, explore secret realms, and encounter fortuitous events, yielding random opportunities—truly wondrous.',
  'ui.tutorialDone': 'Tutorial complete. May your immortal path be smooth.',
  'ui.unlockReward': 'Unlock reward:',
  'ui.xi': 'line',
  'ui.xianluNeed': 'Requires <b>',
  'ui.xiuRate': 'Cultivation Rate',
  'ui.youliBody2': '(as opposed to secluded cultivation: seclusion trades for Power, travel trades for resources)',
  'ui.youliS1': 'Just Starting Out',
  'ui.youliS5': 'Walking the Mortal World',
  'ui.youliY2': 'Ten Years',
  'ui.youliY6': 'Ten Thousand Years',
  'ui.zhanliLack': 'Insufficient Power',
  'ui.zhuEnd': '</b> plants.',
  'combat.affEnd': 'Effect',
  'combat.avatarFo': 'Buddha',
  'combat.cd': 'Cooldown',
  'combat.crit': '(Critical Hit)',
  'combat.dmgUnit': 'Damage',
  'combat.fleeFail': 'Escape Failed!',
  'combat.got': 'Obtained:',
  'combat.lostTo': 'Lost to',
  'combat.reflectDmg2': 'Reflect',
  'combat.shieldUnit': 'Shield',
  'combat.win': 'You defeated your opponent!',
  'cult.breakFailLoss': 'Breakthrough failed. Lost',
  'cult.chooseYouli': 'Select Travel Duration',
  'cult.enlightenOk': 'Enlightenment Succeeded! Comprehension up to',
  'cult.fortune': 'Encountered a rare opportunity. Extra gained',
  'cult.hardWinMid': 'Success! Tribulation Afterglow: Cultivation rate +',
  'cult.layer': 'Layer',
  'cult.lifeLack': 'Lifespan insufficient. Remaining',
  'cult.lingTreasure': 'Spirit Stones and many treasures',
  'cult.needZhanliPre': 'Requires Power first',
  'cult.pctPerm': ')% permanently retained',
  'cult.protectResolvePre': 'Protector consumes',
  'cult.realm': 'Realm!',
  'cult.reincarnatePillPre': 'Reincarnation',
  'cult.shiEnd': ' lives)',
  'cult.startCult': 'Start Cultivation',
  'cult.wuxingMax': 'Comprehension has reached perfection. No further enlightenment.',
  'cult.yearGainPre': ' years. Gained',
  'cult.yuhua': 'Lifespan depleted. Ascended into the void...',
  'cult.zhanliLackBreak': 'Insufficient Power. Cannot Break Through!',
  'cult.zhongEnd': ' fold',
  'expl.avatar': '·Avatar',
  'expl.beggarTeach': 'A beggar imparted the Five Elements Art to you!',
  'expl.bidOk': 'Bid successful:',
  'expl.chestLog': 'Treasure chest encounter: gained',
  'expl.curStone': 'Current Spirit Stones:',
  'expl.enterLog': 'Entered',
  'expl.gainItemLog': 'Gained',
  'expl.havePet': 'You already own a Spirit Beast. The Dragon King bestows 3 Spirit Pearls.',
  'expl.loseHp': 'Lost',
  'expl.noStone': 'Insufficient Spirit Stones',
  'expl.oldStall': "Old Man's Stall",
  'expl.realmLow': 'Insufficient Realm. Requires',
  'expl.sec': 's)',
  'expl.suppress': '(Realm Suppression)',
  'friend.empty': '(Empty)',
  'friend.sep': ', ',
  'inv.alchemyBigLog': 'Grand alchemy success,',
  'inv.bracketEnd': ']',
  'inv.catchPet': 'Tamed Spirit Beast:',
  'inv.enhCost': '(Cost',
  'inv.enhTo': 'Enhanced to +',
  'inv.equipped': 'Equipped:',
  'inv.gain': 'Gained',
  'inv.learnGf': 'Learned Technique:',
  'inv.lingBattle': 'Spirit Energy (active in combat)',
  'inv.noStone': 'Insufficient Spirit Stones! Requires',
  'inv.permAll': 'Permanent +',
  'inv.permDef': 'Permanent Defense +',
  'inv.petOwned': 'Already subdued this Spirit Beast',
  'inv.sell': 'Sell',
  'inv.topQuality': 'Supreme',
  'inv.unequipGfLog': 'Unequipped Technique',
  'main.av.dao': 'Dao',
  'main.byName': 'You take',
  'main.confirmReset': 'Confirm Reset',
  'main.delSaveQ': '” save file?',
  'main.elem.earth': 'Earth Spirit Root',
  'main.elem.wood': 'Wood Spirit Root',
  'main.hrAgo': 'hours ago',
  'main.lifeEnd': 'Lifespan exhausted',
  'main.moAgo': 'months ago',
  'main.reincarnate': 'Re-enter Reincarnation',
  'main.saveOk': 'Save successful',
  'main.stepXian': "'s name, and step onto the Immortal Path",
  'main.tip2': 'The Dao follows nature; stillness and inaction...',
  'main.welcome': 'Welcome to the Immortal Path,',
  'save.capLog': "This life's Power has reached the cap. Go to 'Reincarnation' to rebuild your Dao foundation.",
  'save.migrateFail': 'Old save migration failed:',
  'save.serializeFail': 'Save skipped: serialization failed, old save retained.',
  'shop.buyOk': 'Purchase successful:',
  'shop.realm': 'Realm',
  'ui.addFriendLog': 'Added Fellow Cultivator',
  'ui.atkBonus': 'Attack Bonus',
  'ui.av.xian': 'Immortal',
  'ui.bagEmpty': 'The Qiankun Pouch is empty.',
  'ui.breakNeed': 'Breakthrough requires',
  'ui.buyHerb': 'Buy Reincarnation Herb (',
  'ui.capCurrent': 'You are currently at <b>',
  'ui.careful': 'attribute. Beware!',
  'ui.chengQuMid': '(Law ×',
  'ui.claimed2': 'Claimed',
  'ui.confirmDecomp': 'Confirm Decompose',
  'ui.confirmTitle': 'Confirm',
  'ui.cooldown': '· Cooldown:',
  'ui.createAvatarOk': 'Avatar created successfully.',
  'ui.decompBody': 'Confirm disassemble this equipment? You will receive some Spirit Stones and materials.',
  'ui.delFriend': 'Deleted Fellow Cultivator',
  'ui.elemRestrain': 'Attribute counters opponent',
  'ui.enlightenTitle': 'Enlightenment · Comprehension',
  'ui.evoPill': 'Transformation Pill',
  'ui.evolveOk': 'Spirit Beast transformation complete! Evolved to',
  'ui.exTier2': '1M Power',
  'ui.exchange': 'Exchange',
  'ui.exhaustLife': 'Exhaust all lifespan',
  'ui.feed': 'Feed',
  'ui.fighting': 'Send to Battle',
  'ui.forge': 'Forge',
  'ui.freeRbMid': "</b> (Power cap rises with each Reincarnation; also the <b>current life's Power growth limit</b>. After reaching it, Power stops increasing). Current Power:",
  'ui.giftFrom': " ’s gift:",
  'ui.herbRbMid': '(Each plant',
  'ui.hp': 'HP:',
  'ui.intro': 'Introduction:',
  'ui.learnTalent': 'Learn (+1)',
  'ui.lifeLack': 'Lifespan insufficient',
  'ui.lingShi': 'Spirit Stones',
  'ui.lingShiNian': 'Spirit Stones ·',
  'ui.lvParen': '(Lv.',
  'ui.minute': 'minutes',
  'ui.needGuard': 'Protector requires:',
  'ui.nextStep': 'Next Step',
  'ui.noChar': 'No character created yet',
  'ui.noMatch': 'No matching item found',
  'ui.none': '— None —',
  'ui.offlineNote': '(Offline cultivation efficiency is 50% of online)',
  'ui.own': 'Owned:',
  'ui.pauseCult': 'Pause Cultivation',
  'ui.petFood': 'Spirit Beast Feed',
  'ui.pillRbTail': ', Reincarnation tier +1: permanent HP/Attack bonus; cultivation gains another +100% (permanent).',
  'ui.progress': 'Progress:',
  'ui.rbAtk': ' · Attack ×',
  'ui.readStory': 'Read',
  'ui.realmCurTail': ' Great Realm ·',
  'ui.realmToLearn': 'Realm required to learn',
  'ui.recvLog': 'Received',
  'ui.review': 'Review',
  'ui.seclHint': ' · Seclusion greatly boosts Power (each year in Seclusion costs one year of lifespan)',
  'ui.seclS4': 'The Great Dao Awaits',
  'ui.secludeTitle': 'Seclusion',
  'ui.sellConfirm': 'Confirm Sale',
  'ui.shengJie': 'Upgrade (',
  'ui.shiWillGet': ' lives) will gain:',
  'ui.slotArmor': 'Armor',
  'ui.startCult': 'Start Cultivation',
  'ui.takeIt': 'Take',
  'ui.thInject': 'Injection Rate',
  'ui.thNo': 'No.',
  'ui.totalParen': '(Total',
  'ui.tribAfter': '✨ Tribulation Afterglow',
  'ui.tribLose': 'Tribulation Failed',
  'ui.tribWin': 'Tribulation Succeeded',
  'ui.tut10.title': 'Qiankun Pouch',
  'ui.tut12.title': 'Fellow Cultivator',
  'ui.tut14.title': 'Spirit Beast Training',
  'ui.tut16.title': 'Realm Overview',
  'ui.tut18.title': 'Realm Codex',
  'ui.tut2.title': 'Quiet Cultivation',
  'ui.tut4.title': 'Break Through Realm',
  'ui.tut6.title': 'Lifespan Depleting',
  'ui.tut8.title': 'Three Realms Trial',
  'ui.type': 'Type:',
  'ui.unlockRewardGift': '🎁 Unlock Reward:',
  'ui.xianluHint': "To view all Realms and each life's Reincarnation Power cap, tap the Realm button at the bottom left.",
  'ui.xianluStep': '</b> Realm required to enter (current:',
  'ui.year': 'years',
  'ui.youliGain': 'About +',
  'ui.youliS2': 'Roam the Four Seas',
  'ui.youliS6': 'Seas to Fields',
  'ui.youliY3': '50 years',
  'ui.your': 'Your',
  'ui.zhanliUnit': ' Power',
  'ui.zhuXiuLian': 'Primary Cultivation',
  'combat.attack': 'Attack',
  'combat.avatarMo': 'Demon',
  'combat.colon': ':',
  'combat.dealDmg': ', deals',
  'combat.dropGot': 'Drops obtained:',
  'combat.fleeOk': 'Successfully fled',
  'combat.hpUnit': 'HP',
  'combat.protectShield': ', shielding master',
  'combat.restoreHp': ', restoring',
  'combat.start': 'Battle begins!',
  'combat.winToast': 'Victory! Gained',
  'cult.breakFx': 'Breakthrough!',
  'cult.congrats': 'Congratulations on breakthrough to',
  'cult.exchangeLittle': 'Too few spirit stones gained from exchange',
  'cult.freeRebirthEnd': '(Power cap rises with each reincarnation) to enable free reincarnation',
  'cult.hardWinPre': 'Tank through',
  'cult.layerProgress': 'Realm refined, talent point +1',
  'cult.lingRare': ' Spirit stones and rare treasures!',
  'cult.lingtai': 'Mind serene, comprehension reaches level ',
  'cult.pauseCult': 'Pause cultivation',
  'cult.pillLogEnd': ' reincarnations, dao foundation grows ever stronger',
  'cult.qiji': 'Qi flows, power grows steadily',
  'cult.rebirthCapEnd': ' reincarnations, no further reincarnation possible',
  'cult.safePass': ', safely endured (cultivation rate +',
  'cult.shiFree': ' reincarnations, rebuild your dao foundation (life/attack bonus and cultivation gain +',
  'cult.stoneLackPre': 'Not enough spirit stones, breakthrough needs',
  'cult.xiuGainEnd': ' · Cultivation gain +',
  'cult.yearGetPre': 'years, gained',
  'cult.zhanliCostLife': 'Power (consumes lifespan',
  'cult.zhanliLossMid': 'Power, lifespan -',
  'cult.zhu': ' plants',
  'expl.beggarGone': 'The beggar walks away',
  'expl.beggarTeachLog': 'Beggar teaches Five Elements Art',
  'expl.buy': 'Buy',
  'expl.claimReward': 'Claim reward:',
  'expl.dragonAllow': 'Dragon King permits you to subdue',
  'expl.excl': '!',
  'expl.giveup': 'Give up',
  'expl.hp': 'HP',
  'expl.luckyLog': 'Lucky encounter: gained',
  'expl.noStoneDragon': 'Not enough spirit stones, Dragon King displeased',
  'expl.pickScene': 'Please select a scene first',
  'expl.realmLow2': 'Realm',
  'expl.startPrice': 'Starting bid:',
  'expl.zhanli': 'Power',
  'friend.insufficientGift': 'Insufficient gift quantity',
  'friend.stone': 'Spirit Stones',
  'inv.alchemyLog': 'Refined pill ',
  'inv.breakPill': 'Barrier-Breaking Pill used, next breakthrough success rate +20%',
  'inv.catchPetLog': 'Subdued spirit beast ',
  'inv.enhCostEnd': 'Power)',
  'inv.enhUse': ', costing',
  'inv.excl': '!',
  'inv.gainZhanli': 'Gained',
  'inv.learnSkill': 'Learned ability:',
  'inv.matLack': 'Insufficient materials:',
  'inv.noZhanli': 'Insufficient Power! Need',
  'inv.permAllAtk': 'Attack +',
  'inv.permHp': 'Permanent HP+',
  'inv.realmLow': 'Realm too low, need',
  'inv.skillLearned': 'Already learned this skill',
  'inv.turns': '(',
  'inv.unequipped': 'Unequipped:',
  'main.av.fo': 'Buddha',
  'main.cancel': 'Cancel',
  'main.daotu': "'s dao path",
  'main.delSaveTitle': 'Delete Save',
  'main.elem.fire': 'Fire Spirit Root',
  'main.emptySlot': 'Empty Slot',
  'main.irrev': 'Irreversible',
  'main.lifeEndBody1': 'Fellow Cultivator secluded in cultivation, lifespan finally exhausted,',
  'main.newXianyuan': 'Open new immortal destiny',
  'main.resetBody': '<p style="color:#f43f5e">This operation will <strong>permanently delete</strong> all your game progress!</p><p style="margin-top:10px">Are you sure you want to reset?</p>',
  'main.saveUnavail': '⚠️ Save feature unavailable',
  'main.switchedTo': 'Switched to "',
  'main.tip3': 'Sink qi into dantian, focus on the mystic gate...',
  'main.xiulian': 'Cultivate',
  'save.capReached': 'Power has reached the cap of this life, cultivation income stalled—continue growing only after reincarnation!',
  'save.noSlot': 'Save failed: no save slot specified',
  'save.serializeFatal': 'Serialization failed completely:',
  'shop.needRealm': 'Requires',
  'shop.realmLow': 'Realm too low',
  'ui.addedFriend': 'Added Fellow Cultivator:',
  'ui.av.dao': 'Dao',
  'ui.avatarSummary': 'Created <b>',
  'ui.battleEffect': 'Battle effect:',
  'ui.breakTo': 'Breakthrough to',
  'ui.buyHint': '(If insufficient, buy directly above)',
  'ui.capCurrentMid': '</b> lives This life Power cap: <b class=',
  'ui.caveHint': 'Blessed Cave multipliers: spirit vein +0.08/level, herb garden +0.05, enlightenment cliff +0.10; cave produces spirit stones/comprehension exp per second',
  'ui.chuangJianHuaShen': 'Create incarnation (',
  'ui.close': 'Close',
  'ui.confirmFreeRb': 'Confirm free reincarnation?',
  'ui.consume': 'Consume',
  'ui.cost': 'Cost ',
  'ui.crit': 'Critical hit:',
  'ui.decompConfirm': 'Confirm disassembly',
  'ui.dongTian': '🏞 Blessed Cave',
  'ui.elemRestrainYou': 'Element counters you',
  'ui.eqFurnace': '⚒ Forge · Artifact crafting (materials + spirit stones, quality by luck: mortal→spirit→treasure→immortal→divine)',
  'ui.evolve': 'Form Evolution',
  'ui.exBtn': 'Exchange',
  'ui.exTier3': '10 million Power',
  'ui.exchangeOk': 'Exchange success: consumed',
  'ui.exp': 'EXP ',
  'ui.feedFail': 'Feeding failed',
  'ui.finish': 'Finish',
  'ui.forgeQuality': 'Forge quality:',
  'ui.freeRbNeed': 'Free reincarnation needs Power <b>',
  'ui.giftFromLog': ' Gift:',
  'ui.herbRbNeed': 'Reincarnation Grass needs ',
  'ui.hpBonus': 'HP Bonus',
  'ui.jiLian': 'Refine (',
  'ui.leiji': 'Cumulative',
  'ui.ling': 'Spirit Energy:',
  'ui.lingShiBaowu': 'Spirit Stones · includes random treasure',
  'ui.lingShiPerZhu': 'Spirit Stones/plant)',
  'ui.manCeng': '(Max tier)',
  'ui.modalDefault': 'Notice',
  'ui.needHerb': 'Need ',
  'ui.nian': 'Year',
  'ui.noFriends': 'No Fellow Cultivators yet, share your profile code with friends~',
  'ui.noPet': 'No spirit beast subdued yet',
  'ui.none2': 'None',
  'ui.offlineTail': ', realized:',
  'ui.paren': ')',
  'ui.period': '.',
  'ui.pill': 'Pill',
  'ui.power': 'Power',
  'ui.prologue': '◇ Prologue',
  'ui.rbBonus': 'HP ×',
  'ui.realmCurEnd': ' stage)',
  'ui.realmCurrent': 'You are currently: <b>',
  'ui.realmUnit': 'Realm',
  'ui.remove': 'Remove',
  'ui.reward': 'Reward:',
  'ui.seclS1': 'First Glimpse',
  'ui.seclS5': 'Seven Days in the Cave',
  'ui.secludeToast': 'Seclusion',
  'ui.setMain': 'Set as Main',
  'ui.shengZhi': 'Upgrade to',
  'ui.slideLeft': 'Slide left',
  'ui.slotFabao': 'Treasure',
  'ui.stoneGain': 'Spirit Stone Gain',
  'ui.tap': 'Tap',
  'ui.thLaw': 'Law',
  'ui.thOp': 'Action',
  'ui.train': 'Cultivate',
  'ui.tribBonus': 'Tribulation bonus: cultivation +',
  'ui.tribSafe': '🛡 Safe Tribulation',
  'ui.tut1.body': '<b>Divine Abilities</b> let you learn spells to cast in battle. Offense, defense, and support each have their uses; the deeper your technique, the greater the power—your confidence to fight beyond your rank and explore secret realms.',
  'ui.tut11.body': '<b>Power Cap</b> is a power threshold that rises with each reincarnation, and also the <b>max power growth for this life</b>—once power hits the cap it stops rising (realms no longer have a separate ceiling). At that point you can <b>free reincarnate</b> to raise the cap: rebuild your dao foundation, reset realm and lifespan, yet <b>permanently keep</b> your HP and attack bonuses. Each reincarnation grants <b>+100% permanent cultivation gain</b> (life N cultivation speed ×(1+N)), and HP/attack each ×(1+0.3N); reincarnation limit is <b>100 lives</b>. You may also spend <b>100 Reincarnation Grass</b> (sold in the market) to reincarnate directly, bypassing the threshold. The rebirth panel now shows your <b>reincarnation tier</b> separately.',
  'ui.tut13.body': '<b>Talents</b> are long-term growth across your dao path: every <b>major realm breakthrough</b> awakens a talent point (every 5 minor realms grants 1 more). In the <b>Cultivation · Talent</b> sub-tab, train six talent trees (Offense/Defense/Longevity/Comprehension/Beast Taming/Heavenly Fate) for permanent boosts to attack, defense, cultivation, spirit stones, combat, and tribulation.',
  'ui.tut15.body': 'After reaching the <b>Great Dao</b> realm, the <b>Dao</b> icon on the sidebar lights up. Enter the <b>Immortal Path</b> panel to gradually unlock four <b>independent multiplier zones</b>, stacked after Realm/Equipment/Spirit Beast/Reincarnation/Talent, <b>non-diluting</b>—<br>• <b>Law Comprehension</b>: six laws (Sword/Pill/Array/Time-Space/Cause-Effect/Reincarnation), 5 tiers each, each tier a separate multiplier, tier-up = permanent multiplier<br>• <b>Life-Bound Treasure</b>: 5 treasures, 30 levels, with unique combat effects (lifesteal/reflect/shield/first-strike/true damage)<br>• <b>Blessed Cave</b>: spirit vein/herb garden/enlightenment cliff, 3 plots of 20 levels, passively producing spirit stones/comprehension exp, independent multiplier<br>• <b>Clone Avatar</b>: up to 3 avatars (One Qi to Three Pure Ones), injecting into the power pool by a ratio of your main cultivation rate (not into combat stats)<br>※ This is the late-game core growth path; raise each item at your <b>spirit stone</b> pace.',
  'ui.tut17.body': '<b>Quests</b> point the way, the <b>Market</b> supplies resources, <b>Fellow Cultivators</b> debate and compete. The immortal road is long—take good care, and go!',
  'ui.tut19.body': '<b>Secluded cultivation</b> trades for massive power; <b>travel the world</b> to find spirit stones, materials, and pills; <b>exchange spirit stones</b> to trade power for spirit stones. All three consume <b>lifespan</b>.',
  'ui.tut3.body': '<b>Epiphany</b> spends spirit stones or power to raise <b>comprehension</b>. The higher your comprehension, the more <b>power per click</b> and <b>cultivation rate</b> surge—this is the key engine for sprinting to high realms late game (Mahayana and above). The earlier you epiphany, the longer you benefit; one year of seclusion equals a thousand years past.',
  'ui.tut5.body': '<b>Epiphany</b> spends spirit stones or power to raise <b>comprehension</b>. The higher your comprehension, the more <b>power per click</b> and <b>cultivation rate</b> surge—this is the key engine for sprinting to high realms late game (Mahayana and above). The earlier you epiphany, the longer you benefit; one year of seclusion equals a thousand years past.',
  'ui.tut7.body': 'Switch to <b>Combat</b> to debate dao with beasts; victory grants power, spirit stones, and drops, and also tempers your dao heart.',
  'ui.tut9.body': 'Switch to the <b>Market</b> to buy and sell goods and hunt for treasures. Equipment, pills, techniques, treasures, and spirit beasts are all tradable; the <b>Reincarnation Grass</b> needed for cultivation is bought directly in the Reincarnation panel.',
  'ui.unequip': 'Unequip',
  'ui.upgrade': 'Upgrade',
  'ui.xianluLayer': 'tier)<br><span class=',
  'ui.xiuBonus': 'Cultivation Gain',
  'ui.you': '(You)',
  'ui.youliResult': 'Travel',
  'ui.youliS3': 'Roam Famous Mountains',
  'ui.youliTitle': 'Travel the World',
  'ui.youliY4': 'Century',
  'ui.yourTurn': '⚔ Your Turn',
  'ui.zhong': ' weight',
  'ui.zongChengQu': 'Total multiplier:',
        // —— 修炼/闭关/兑换 详情（补漏） ——
        'ui.zhanli': 'Power',
        'ui.noCap': ' (cap lifted — no upper limit)',
        'ui.capNone': ' (no upper limit)',
        'ui.capReached': ' reached the cap — free Reincarnation raises the next life',
        'ui.secludeBody1': 'Seclusion severs mortal ties and deepens the Dao. Longer seclusion yields more Power, but <b>each year secluded costs one year of lifespan</b>. Current lifespan: <b>${fmtNum(p.lifespan || 0)} years</b>.',
        'ui.secludeBody2': '(Lifespan is the seclusion cap; you cannot seclude beyond your lifespan. Each major-realm breakthrough extends lifespan. <b>Note: higher cultivation rate means diminishing per-unit seclusion gains, capping at very high realms.</b>)',
        'ui.exchangeBody1': 'Exchange <b>Power</b> for <b>Spirit Stones</b>, used for breakthroughs and the Market. Current Power: <b>${fmtNum(p.zhanli || 0)}</b>.',
        'ui.exchangeBody2': 'Rate: ~${fmtNum(2000)} Power ≈ 1 Spirit Stone. Exchanged stones do not count toward quests; exchanging consumes Power and may slow breakthroughs — weigh carefully.',
        'ui.enlightenBody': 'Cultivation Insight permanently boosts <b>Power per tap</b> and slightly raises <b>cultivation rate</b>. Current Insight: <b>${lv} stage</b> (tap +${tapNow}% · rate +${rateNow}%). After insight → tap +${tapNext}% · rate +${rateNext}%.',
        'ui.enlightenMax': 'Insight has reached perfection (<b>${max} stage</b>); cannot deepen further.'
    },

    /* 数据译名：按中文原串查表（境界 103 + 五行 5 + 品质 5） */
    DATA: {
        // ===== 103 大境界 =====
        '练气': 'Qi Refining', '筑基': 'Foundation', '金丹': 'Golden Core', '元婴': 'Nascent Soul',
        '化神': 'Spirit Transformation', '炼虚': 'Void Refinement', '合体': 'Integration', '大乘': 'Mahayana',
        '真仙': 'True Immortal', '金仙': 'Golden Immortal', '太乙': 'Taiyi', '大罗': 'Daluo',
        '道祖': 'Dao Ancestor', '道君': 'Dao Sovereign', '道尊': 'Dao Venerable', '道圣': 'Dao Sage',
        '混元': 'Primordial Unity', '太上': 'Supreme', '无量': 'Boundless', '鸿钧': 'Hongjun',
        '天道': 'Heavenly Dao', '天尊': 'Heavenly Venerable', '圣人': 'Sage', '太初': 'Primordial Beginning',
        '太易': 'Primordial Ease', '太极': 'Supreme Polarity', '先天': 'Innate', '混沌': 'Chaos',
        '鸿蒙': 'Hongmeng', '无极': 'Wuji', '永恒': 'Eternal', '虚无': 'Voidness',
        '大道': 'Great Dao', '玄元': 'Mysterious Origin', '太虚': 'Great Void', '太昊': 'Taihao',
        '太清': 'Taiqing', '玉清': 'Yuqing', '上清': 'Shangqing', '紫府': 'Purple Mansion',
        '灵霄': 'Spirit Firmament', '九霄': 'Nine Firmaments', '神霄': 'Divine Firmament', '太微': 'Taiwei',
        '太玄': 'Taixuan', '元始': 'Yuanshi', '虚空': 'Emptiness', '太素': 'Taisu',
        '太始': 'Taishi', '无上': 'Unfathomable', '无涯': 'Endless', '无相': 'Formless',
        '无垢': 'Stainless', '圆明': 'Perfect Radiance', '圆觉': 'Perfect Enlightenment', '真如': 'Suchness',
        '自在': 'Freedom', '逍遥': 'Wandering Free', '大觉': 'Great Awakening', '大衍': 'Dayan',
        '渺渺': 'Misty', '冥冥': 'Obscure', '浩渺': 'Vast', '苍穹': 'Firmament',
        '寰宇': 'Cosmos', '乾坤': 'Qiankun', '玄黄': 'Xuanhuang', '寂灭': 'Cessation',
        '涅槃': 'Nirvana', '归真': 'Return to Truth', '返璞': 'Return to Simplicity', '合一': 'Unity',
        '同尘': 'One with Dust', '玄同': 'Mysterious Unity', '守一': 'Guard the One', '抱朴': 'Embrace Simplicity',
        '至善': 'Supreme Good', '至诚': 'Ultimate Sincerity', '至道': 'Ultimate Dao', '究竟': 'Ultimate',
        '无碍': 'Unobstructed', '无为': 'Non-Action', '太一': 'The One', '太苍': 'Taicang',
        '太渊': 'Taiyuan', '太真': 'Taizhen', '太元': 'Taiyuan Prime', '太明': 'Taiming',
        '太光': 'Taiguang', '太宁': 'Taining', '太安': 'Taian', '太恒': 'Taiheng',
        '太润': 'Tairun', '太白': 'Taibai', '太阿': 'Tai\'e', '太皇': 'Taihuang',
        '太衍': 'Taiyan', '太昭': 'Taizhao', '太曦': 'Taixi', '太华': 'Taihua',
        '太岳': 'Taiyue', '太溟': 'Tai Ming (Sea)', '太寥': 'Tailiao',
        // ===== 五行 =====
        '金': 'Metal', '木': 'Wood', '水': 'Water', '火': 'Fire', '土': 'Earth',
        // ===== 品质 =====
        '凡品': 'Mortal', '灵品': 'Spiritual', '宝品': 'Treasure', '仙品': 'Immortal', '神品': 'Divine',
        // ===== 天赋六系 =====
        '攻伐': 'Attack', '守御': 'Defense', '长生': 'Longevity', '悟道': 'Enlightenment', '御兽': "Beast Taming", '天命': "Heaven's Mandate",
        '九天雷劫':'Nine-Heaven Thunder Tribulation',
        '心魔大劫':'Inner Demon Tribulation',
        '无量业火':'Boundless Karma Fire',
        '寒铁短剑':'Cold Iron Short Sword',
        '烈焰刀':'Flame Blade',
        '七弦灵琴':'Seven-String Spirit Zither',
        '紫电雷剑':'Purple Lightning Thunder Sword',
        '混沌剑':'Chaos Sword',
        '青锋枪':'Green Edge Spear',
        '日月轮':'Sun-Moon Wheel',
        '盘古斧':'Pangu Axe',
        '麻布道袍':'Linen Dao Robe',
        '云纹锦袍':'Cloud-Pattern Brocade Robe',
        '灵纹战甲':'Spirit-Rune Battle Armor',
        '星辉仙衣':'Starlight Immortal Garment',
        '混沌道袍':'Chaos Dao Robe',
        '青铜镜':'Bronze Mirror',
        '青云袍':'Green Cloud Robe',
        '天蚕衣':'Sky-Silk Garment',
        '灵玉佩':'Spirit Jade Pendant',
        '炎火戒':'Flame Fire Ring',
        '灵纹束带':'Spirit-Rune Sash',
        '星辰坠':'Star Pendant',
        '混沌珠':'Chaos Pearl',
        '风灵符':'Wind Spirit Talisman',
        '龙玉珏':'Dragon Jade Pendant',
        '太虚珠':'Great Void Pearl',
        '小金钟':'Small Golden Bell',
        '须弥小山':'Sumeru Hill',
        '阴阳镜':'Yin-Yang Mirror',
        '七宝玲珑塔':'Seven-Treasure Exquisite Pagoda',
        '玉如意':'Jade Ruyi',
        '招魂幡':'Soul-Summoning Banner',
        '聚气丹':'Qi-Gathering Pill',
        '回春丹':'Rejuvenation Pill',
        '筑基丹':'Foundation Pill',
        '虎力丹':'Tiger Strength Pill',
        '金刚丹':'Vajra Pill',
        '破障丹':'Barrier-Breaking Pill',
        '培元丹':'Vitality Pill',
        '锻骨丹':'Bone-Forging Pill',
        '九转金丹':'Nine-Turn Golden Pill',
        '大还丹':'Great Restoration Pill',
        '聚灵丹':'Spirit-Gathering Pill',
        '凝神丹':'Spirit-Focusing Pill',
        '灵草':'Spirit Herb',
        '灵矿':'Spirit Ore',
        '妖兽内丹':'Demon Beast Core',
        '灵珠':'Spirit Pearl',
        '混沌石':'Chaos Stone',
        '灵木':'Spirit Wood',
        '庚金':'Geng Metal',
        '精气':'Essence Qi',
        '轮回草':'Reincarnation Herb',
        '基础吐纳术':'Basic Breathing Art',
        '五行诀':'Five-Element Art',
        '紫气东来':'Purple Qi Coming East',
        '混沌造化功':'Chaos Creation Art',
        '太上感应篇':'Supreme Sensing Scripture',
        '虚空炼神诀':'Void Spirit-Refining Art',
        '一击':'Single Strike',
        '剑气斩':'Sword Qi Slash',
        '火球术':'Fireball Technique',
        '寒冰矢':'Ice Arrow',
        '回春术':'Rejuvenation Technique',
        '土盾术':'Earth Shield Technique',
        '雷霆万钧':'Thunder Crush',
        '焚天烈焰':'Burning Sky Flame',
        '连珠诀':'Chain Pearl Art',
        '封魂印':'Soul-Sealing Seal',
        '混沌斩':'Chaos Slash',
        '仙法·万剑归宗':'Immortal Art: Ten-Thousand Swords Return',
        '玄元无极功':'Mysterious Void Infinite Art',
        '太清剑诀':'Supreme Purity Sword Art',
        '紫霄神雷':'Purple Heaven Divine Thunder',
        '离火焚天':'Li Fire Burning Sky',
        '玄天镇魔':'Mysterious Heaven Demon-Suppressing',
        '儒尊·浩然':'Confucian Sage Haoran',
        '道·无上':'Supreme Dao Art',
        '金钟护体':'Golden Bell Bodyguard',
        '泰山压顶':'Mount Tai Press Down',
        '阴阳反照':'Yin-Yang Reflection',
        '万法镇灭':'Ten-Thousand Laws Suppression',
        '玄狼':'Mysterious Wolf',
        '玄龟':'Mysterious Turtle',
        '火凤':'Fire Phoenix',
        '青龙':'Azure Dragon',
        '撕咬':'Bite',
        '护主':'Master Protection',
        '烈焰吐息':'Flame Breath',
        '龙吟':'Dragon Roar',
        '山野妖狼':'Mountain Wild Demon Wolf',
        '吸血妖蝠':'Blood-Sucking Demon Bat',
        '青鳞蛇妖':'Green-Scale Snake Demon',
        '玄铁熊':'Mysterious Iron Bear',
        '邪修散人':'Evil Cultivator Rogue',
        '赤焰虎王':'Red Flame Tiger King',
        '魔修宗师':'Demon Cultivator Grandmaster',
        '蛟龙':'Flood Dragon',
        '幽冥鬼王':'Nether Ghost King',
        '天魔':'Heavenly Demon',
        '渡劫真仙':'Tribulation True Immortal',
        '炼虚魔君':'Void-Refining Demon Lord',
        '合体妖尊':'Unity Demon Venerate',
        '大乘罗汉':'Mahayana Arhat',
        '真仙使者':'True Immortal Envoy',
        '金仙老祖':'Gold Immortal Ancestor',
        '太乙天尊':'Taiyi Heavenly Venerate',
        '大罗金仙':'Daluo Gold Immortal',
        '道祖化身':'Dao Ancestor Avatar',
        '本门宗':'Own Sect',
        '青云坊市':'Green Cloud Market',
        '万妖林':'Ten-Thousand Demons Forest',
        '灵矿洞':'Spirit Ore Cave',
        '上古秘境':'Ancient Secret Realm',
        '东海龙宫':'East Sea Dragon Palace',
        '混沌秘境':'Chaos Secret Realm',
        '九重天':'Nine Heavens',
        '诸天战场':'All-Heavens Battlefield',
        '静修悟道':'Silent Cultivation Insight',
        '师尊指点':'Master Guidance',
        '宗门任务':'Sect Mission',
        '偶遇摊位':'Chance Stall Encounter',
        '拍卖盛会':'Auction Event',
        '乞丐乞讨':'Beggar Begging',
        '妖兽袭击':'Demon Beast Attack',
        '发现灵草':'Discover Spirit Herb',
        '迷路弟子':'Lost Disciple',
        '发现矿脉':'Discover Ore Vein',
        '矿工冲突':'Miner Conflict',
        '矿洞坍塌':'Mine Collapse',
        '宝箱奇遇':'Treasure Chest Encounter',
        '上古凶兽':'Ancient Fierce Beast',
        '道统传承':'Dao Lineage Inheritance',
        '龙族考验':'Dragon Clan Trial',
        '海底宝库':'Seabed Treasure Vault',
        '幼龙求收':'Young Dragon Seeking Master',
        '混沌传承':'Chaos Inheritance',
        '混沌凶兽':'Chaos Fierce Beast',
        '仙人指路':'Immortal Guidance',
        '初识修炼':'First Cultivation',
        '初战告捷':'First Victory',
        '突破练气':'Breakthrough to Qi Refining',
        '筑基大道':'Foundation Great Dao',
        '历练初探':'First Exploration',
        '斩妖除魔':'Slay Demons',
        '结丹大道':'Core Formation Great Dao',
        '威震四方':'Fame Shakes All Sides',
        '元婴大道':'Nascent Soul Great Dao',
        '化神飞升':'Spirit Transformation Ascension',
        '壹·凡尘微光':'One: Mortal Dust Faint Light',
        '贰·筑基立道':'Two: Foundation Establishes Dao',
        '叁·金丹一颗':'Three: One Golden Core',
        '肆·元婴睁眼':'Four: Nascent Soul Opens Eyes',
        '伍·化神之疑':'Five: Spirit Transformation Doubt',
        '陆·炼虚窥隙':'Six: Void Refining Peers Gap',
        '柒·合体同源':'Seven: Unity Same Source',
        '捌·大乘将临':'Eight: Mahayana Approaching',
        '玖·真仙初蜕':'Nine: True Immortal First Transformation',
        '拾·金仙问道':'Ten: Gold Immortal Seeks Dao',
        '拾壹·太乙临霄':'Eleven: Taiyi Descends to Heavens',
        '拾贰·大罗破狱':'Twelve: Daluo Breaks Prison',
        '拾叁·道祖之争':'Thirteen: Dao Ancestor Contest',
        '无名修士':'Nameless Cultivator',
        '回血丹':'Blood-Return Pill',
        '续命丹':'Life-Continuing Pill',
        '九转还魂丹':'Nine-Turn Soul-Return Pill',
        '聚灵散':'Spirit-Gathering Powder',
        '凝灵丹':'Spirit-Condensing Pill',
        '太乙神液':'Taiyi Divine Liquid',
        '冲虚丹':'Void-Rushing Pill',
        '悟道丹':'Dao-Comprehending Pill',
        '破境散':'Realm-Breaking Powder',
        '狂战丹':'Berserk Battle Pill',
        '裂天丹':'Sky-Splitting Pill',
        '玄龟丹':'Mysterious Turtle Pill',
        '镇岳丹':'Mountain-Suppressing Pill',
        '通玄丹':'Mystery-Opening Pill',
        '破障灵丹':'Barrier-Breaking Spirit Pill',
        '玉肌丹':'Jade Skin Pill',
        '不死丹':'Immortality Pill',
        '裂石丹':'Stone-Splitting Pill',
        '霸王丹':'Overlord Pill',
        '戮天丹':'Heaven-Slaying Pill',
        '灵海丹':'Spirit Sea Pill',
        '神识丹':'Divine Sense Pill',
        '玄甲丹':'Mysterious Armor Pill',
        '山岳丹':'Mountain Pill',
        '破军丹':'Army-Breaking Pill',
        '锐锋丹':'Sharp Edge Pill',
        '疾风丹':'Swift Wind Pill',
        '流光丹':'Flowing Light Pill',
        '混元金丹':'Primordial Golden Pill',
        '招财丹':'Wealth-Attracting Pill',
        '青锋剑':'Green Edge Sword',
        '流云剑':'Flowing Cloud Sword',
        '斩月刀':'Moon-Severing Blade',
        '裂空枪':'Void-Splitting Spear',
        '焚天戟':'Sky-Burning Halberd',
        '惊雷锤':'Thunder-Shocking Hammer',
        '太虚环':'Great Void Ring',
        '诛神枪':'God-Slaying Spear',
        '玄龟甲':'Mysterious Turtle Armor',
        '流云袍':'Flowing Cloud Robe',
        '镇魂铠':'Soul-Suppressing Armor',
        '星陨甲':'Star-Falling Armor',
        '太乙道衣':'Taiyi Dao Robe',
        '混元甲':'Primordial Armor',
        '不动明王甲':'Immovable Wisdom King Armor',
        '周天锁子甲':'Heavenly Cycle Chainmail',
        '翠玉环':'Jade Green Ring',
        '疾风铃':'Swift Wind Bell',
        '镇魂玉':'Soul-Suppressing Jade',
        '星辰链':'Star Chain',
        '太虚戒':'Great Void Band',
        '因果环':'Karma Ring',
        '混沌铃':'Chaos Bell',
        '天命珠':'Heaven Mandate Pearl',
        '镇魂塔':'Soul-Suppressing Pagoda',
        '乾坤镜':'Qian-Kun Mirror',
        '万钧锤':'Ten-Thousand Jun Hammer',
        '护心灯':'Heart-Guard Lamp',
        '山河社稷图':'Mountains-Rivers Map',
        '两仪轮':'Two-Forms Wheel',
        '定海神针':'Sea-Calming Divine Needle',
        '九霄环':'Nine-Heaven Ring',
        '太清宝塔':'Supreme Purity Pagoda',
        '诸天鼎':'All-Heavens Cauldron',
        '无衡镜':'Balance Mirror',
        '九转玄功':'Nine-Turn Mysterious Art',
        '太阴虚冥诀':'Taiyin Netherworld Art',
        '两仪微尘诀':'Two-Forms Dust Art',
        '周天星辰诀':'Heavenly Cycle Stars Art',
        '鸿蒙紫气诀':'Hongmeng Purple Qi Art',
        '混元无极功':'Primordial Infinite Art',
        '太清紫极功':'Supreme Purity Purple Pole Art',
        '紫霄混元功':'Purple Heaven Primordial Art',
        '离火焚天功':'Li Fire Burning Sky Art',
        '玄天镇魔功':'Mysterious Heaven Demon-Suppress Art',
        '儒尊浩然功':'Confucian Sage Haoran Art',
        '无上道经':'Supreme Dao Scripture',
        '火云犬':'Fire Cloud Dog',
        '玉兔':'Jade Rabbit',
        '金翅雕':'Gold Wing Eagle',
        '玄武龟':'Black Tortoise',
        '赤焰马':'Red Flame Horse',
        '墨麒麟':'Ink Qilin',
        '白泽':'Baize',
        '朱雀':'Vermilion Bird',
        '祖龙':'Ancestral Dragon',
        '麒麟王':'Qilin King',
        '白泽王':'Baize King',
        '朱雀皇':'Vermilion Bird Empress',
        '祖龙·太初':'Ancestral Dragon: Primordial',
        '破军':'Army Breaker',
        '锐芒':'Sharp Edge',
        '铁壁':'Iron Wall',
        '血海':'Blood Sea',
        '灵渊':'Spirit Abyss',
        '疾风':'Swift Wind',
        '明悟':'Clear Comprehension',
        '点石':'Stone Touch',
        '驭兽':'Beast Taming',
        '通玄':'Mystery Access',
        '逆命':'Fate Reversal',
        '戮仙':'Immortal Slayer',
        '护身':'Body Protection',
        '灵兽粮':'Spirit Beast Feed',
        '化形丹':'Form-Change Pill',
        '剑之法则':'Sword Law',
        '丹之法则':'Pill Law',
        '阵之法则':'Formation Law',
        '时空法则':'Space-Time Law',
        '因果法则':'Karma Law',
        '轮回法则':'Reincarnation Law',
        '本命飞剑':'Life-Bound Flying Sword',
        '本命宝印':'Life-Bound Treasure Seal',
        '本命神钟':'Life-Bound Divine Bell',
        '本命宝塔':'Life-Bound Pagoda',
        '本命元珠':'Life-Bound Origin Pearl',
        '灵脉':'Spirit Vein',
        '药田':'Herb Field',
        '悟道崖':'Dao-Comprehending Cliff',
    },
    DATA_DESC: {
        '攻伐凌厉':'Sharp and fierce attacks.',
        '生生不息':'Endless life and growth.',
        '灵动善变':'Agile and ever-changing.',
        '焚天烈焰':'Sky-burning flames.',
        '厚重如山':'Heavy and stable like a mountain.',
        '天穹裂开，紫霄神雷劈落，淬炼道躯。以攻伐之威硬抗，方显道心。':'The sky splits as purple-heaven divine thunder strikes, tempering the dao body. Endure it with sheer force to prove your dao heart.',
        '心中妄念化形，幻境叠生。需灵台清明、悟性通明方能勘破。':'Inner delusions take form amid layered illusions. Only a clear mind and bright wisdom can see through them.',
        '红莲业火自足底燃起，焚尽业障亦焚道基。须气血雄浑方可熬过。':'Red-lotus karma fire rises from the soles, burning both karmic obstacles and your dao foundation. Only bursting vitality can endure it.',
        '寒铁所铸，锋利无匹':'Forged of cold iron, supremely sharp.',
        '附火灵之力，斩敌如焚':'Infused with fire spirit power, it burns foes as it cuts.',
        '以音杀人，余音绕梁':'Kills with sound, leaving lingering echoes.',
        '雷霆之力凝聚，斩魂灭魄':'Condensed thunder power severs soul and spirit.',
        '混沌之力所化，斩断因果':'Born of chaos power, it cuts all cause and effect.',
        '青锋凛冽，挑刺如龙':'Its green edge is keen, thrusting like a dragon.',
        '日月交辉，轮转破敌':'Sun and moon shine together as the wheel turns to break foes.',
        '开天辟地之威，重若山岳':'World-opening might, heavy as a mountain.',
        '寻常布衣，聊胜于无':'Ordinary cloth, better than nothing.',
        '云纹加持，灵气流转':'Cloud patterns aid the flow of spirit energy.',
        '灵纹铭刻，刀枪不入':'Spirit runes are carved in, blades cannot pierce.',
        '星辉织就，免疫百邪':'Woven of starlight, it wards off all evil.',
        '混沌之力护体，万法不侵':'Chaos power guards the body against all arts.',
        '青铜照影，邪祟难近':'Bronze reflects shadows, keeping evil away.',
        '青云加护，灵气绵长':'Green cloud protection grants lasting spirit energy.',
        '天蚕丝织，刀剑难伤':'Woven of sky silk, blades hardly wound.',
        '灵玉所制，安神定志':'Made of spirit jade, it calms the mind.',
        '炎火凝聚，催动法术':'Condensed flame fire boosts spellcasting.',
        '灵纹铭刻，催发灵力':'Spirit runes carved in stir the spirit power.',
        '星辰之力凝聚，运势加身':'Condensed star power brings fortune.',
        '混沌所凝，道韵流转':'Condensed chaos, with flowing dao rhythm.',
        '风灵萦绕，身法轻盈':'Wind spirits surround, lightening movement.',
        '龙玉温养，灵机盎然':'Dragon jade nurtures, brimming with spirit.',
        '太虚之气所凝，运势加身':'Condensed great-void qi brings fortune.',
        '护身法宝，可挡一击':'A guardian treasure that blocks one strike.',
        '镇压万物，重如泰山':'Suppresses all things, heavy as Mount Tai.',
        '阴阳流转，反弹伤害':'Yin and yang flow, reflecting damage.',
        '镇压一切邪祟，万法归一':'Suppresses all evil, unifying all arts.',
        '招魂摄魄，万灵听令':'Summons souls and commands all spirits.',
        '恢复50灵力':'Restores 50 spirit energy.',
        '恢复100气血':'Restores 100 health.',
        '立即获得200战力':'Grants 200 battle power at once.',
        '战斗中攻击+15（3回合）':'Boosts attack by 15 for 3 turns in battle.',
        '战斗中防御+10（3回合）':'Boosts defense by 10 for 3 turns in battle.',
        '突破成功率+20%':'Raises breakthrough success by 20%.',
        '永久+50气血':'Permanently adds 50 health.',
        '永久+8攻击':'Permanently adds 8 attack.',
        '永久+30攻击 +200气血':'Permanently adds 30 attack and 200 health.',
        '恢复2000气血':'Restores 2000 health.',
        '恢复500灵力':'Restores 500 spirit energy.',
        '永久+200灵力':'Permanently adds 200 spirit energy.',
        '炼丹基础材料':'Basic material for pill refining.',
        '炼器基础材料':'Basic material for equipment forging.',
        '妖兽核心':'Core of a demon beast.',
        '炼丹高级材料':'Advanced material for pill refining.',
        '蕴含混沌之力的奇石':'A rare stone holding chaos power.',
        '温养灵气的奇木':'A rare wood that nourishes spirit energy.',
        '锋锐无比的庚金之精':'The sharpest essence of geng metal.',
        '天地精气凝炼而成':'Condensed from heaven and earth essence.',
        '转世轮回之引，根植幽冥，坊市有售':'A guide to reincarnation, rooted in the underworld, sold in the market.',
        '最基础的修炼功法':'The most basic cultivation method.',
        '调和五行，修炼效率提升':'Harmonizes the five elements and boosts cultivation.',
        '吸纳紫气，道韵加身':'Absorbs purple qi, gaining dao rhythm.',
        '混沌之力，造化万物':'Chaos power creates all things.',
        '太上传承，道法自然':'Supreme inheritance, the dao follows nature.',
        '虚空炼神，道韵自生':'Refines spirit in the void, dao rhythm arises.',
        '基础攻击':'A basic attack.',
        '金属性，凌厉剑气':'Metal element, keen sword qi.',
        '火属性，灼烧敌人':'Fire element, burns the enemy.',
        '水属性，减速敌人':'Water element, slows the enemy.',
        '木属性，恢复气血':'Wood element, restores health.',
        '土属性，护身盾甲':'Earth element, a protective shield.',
        '金属性群雷，强力一击':'Metal element thunder, a powerful strike.',
        '火属性烈焰，灼烧万物':'Fire element flame, burns all things.',
        '连击三次，每次递增':'Three consecutive hits, each stronger.',
        '封印敌人灵力':'Seals the enemy spirit power.',
        '混沌之力斩击，无视防御':'Chaos strike ignores defense.',
        '万剑齐发，灭杀一切':'Ten-thousand swords fly, slaying all.',
        '无极玄力，攻伐凌厉，等级越高威能越盛':'Boundless mystery power, fierce attacks grow stronger with level.',
        '太清仙宗剑诀，一剑化万道清光，大乘修士的杀伐绝学':'Supreme Purity sword art, one sword becomes ten-thousand clear lights, the killing art of Mahayana cultivators.',
        '引紫霄神雷灌体，雷光所至万法崩摧':'Draws purple-heaven divine thunder into the body, shattering all arts where lightning strikes.',
        '离火真炎焚尽八荒，触者形神俱灭':'Li-fire true flame burns the eight wilds, erasing body and soul of those touched.',
        '玄天之力镇封亘古大魔，一击定乾坤':'Mysterious heaven power seals the ancient great demon, deciding the world in one strike.',
        '浩然正气贯长虹，言出法随、灭度诸邪':'Righteous qi pierces the rainbow, words become law and erase all evil.',
        '大道无上，一念生灭轮回，乃诸天至高的攻伐道法':'Supreme great dao, a thought births and ends reincarnation, the highest attacking art of all heavens.',
        '抵挡下一次攻击':'Blocks the next attack.',
        '镇压敌人':'Suppresses the enemy.',
        '反弹50%伤害':'Reflects 50% of damage.',
        '镇压一切':'Suppresses everything.',
        '玄铁狼，攻击型灵宠':'A metal-wolf, an attack-type spirit pet.',
        '玄水龟，防御型灵宠':'A black-water turtle, a defense-type spirit pet.',
        '烈焰火凤，群攻灵宠':'A flame fire-phoenix, an area-attack spirit pet.',
        '上古青龙，至强灵宠':'An ancient azure dragon, the strongest spirit pet.',
        '修行之所，可修炼、接任务':'A cultivation place to train and take missions.',
        '修士云集，交易宝物':'Cultivators gather here to trade treasures.',
        '妖兽横行，历练宝地':'Demon beasts roam, a fine trial ground.',
        '灵矿丰富，藏有奇珍':'Rich in spirit ore, hiding rare treasures.',
        '上古大能遗留，机缘无数':'Left by ancient mighty ones, full of fortune.',
        '龙族居所，宝物云集':'Home of the dragon clan, crowded with treasures.',
        '混沌之力充斥，至强机缘所在':'Filled with chaos power, the seat of ultimate fortune.',
        '大乘以上方可飞升的仙界绝境，云海深处藏着太清传承与诸天重宝':'A heavenly peril reachable only after Mahayana, where Supreme Purity inheritance and all-heaven treasures hide in the sea of clouds.',
        '诸天陨落之古战场，煞气滔天，唯真仙以上可入，夺将臣残魂与战兵':'An ancient battlefield of fallen heavens, thick with killing qi, enterable only above True Immortal, to seize generals remnant souls and war gear.',
        '在此静坐片刻，似有所悟':'Sitting quietly here, you seem to gain insight.',
        '宗门长老路过，见你根基不错，传你一道':'A sect elder passes by, sees your good foundation, and teaches you a method.',
        '掌门召你前去，有一桩差事':'The sect master summons you for a task.',
        '路边一老叟摆摊，似有奇货':'An old man sets a stall by the road, seeming to hold rare goods.',
        '坊市举办拍卖会，有稀有宝物':'The market holds an auction with rare treasures.',
        '一蓬头乞丐拦住去路，声称是有缘人':'A ragged beggar blocks the way, claiming you are fated.',
        '一头妖兽挡住去路！':'A demon beast blocks the path!',
        '路边发现一丛灵草':'A cluster of spirit herb is found by the road.',
        '遇到一位迷路的同门弟子':'You meet a lost fellow disciple.',
        '岩壁上有灵矿显现':'Spirit ore shows on the rock wall.',
        '有散修抢占你的矿位':'A rogue cultivator seizes your mining spot.',
        '矿洞突然坍塌！':'The mine suddenly collapses!',
        '秘境深处发现一个古朴宝箱':'A quaint treasure chest is found deep in the secret realm.',
        '一头上古凶兽苏醒！':'An ancient fierce beast awakens!',
        '前方石台上有上古修士留下的传承':'An ancient cultivator left inheritance on the stone platform ahead.',
        '龙王现身，要考校你的战力':'The dragon king appears to test your battle power.',
        '海底深处隐约有光芒':'Faint light glimmers in the deep seabed.',
        '一条幼龙似乎认主于你':'A young dragon seems to accept you as master.',
        '混沌之力向你涌来':'Chaos power surges toward you.',
        '混沌中窜出一头凶兽！':'A fierce beast darts out of the chaos!',
        '一位仙人现身，问你可愿接受考验':'An immortal appears and asks if you accept a trial.',
        '修炼累积100战力':'Cultivate to reach 100 battle power.',
        '战胜1个敌人':'Defeat 1 enemy.',
        '突破至练气三层':'Break through to Qi Refining layer 3.',
        '突破至筑基境界':'Break through to the Foundation realm.',
        '完成10次探索':'Complete 10 explorations.',
        '战胜20个敌人':'Defeat 20 enemies.',
        '突破至金丹境界':'Break through to the Golden Core realm.',
        '战胜50个敌人':'Defeat 50 enemies.',
        '突破至元婴境界':'Break through to the Nascent Soul realm.',
        '突破至化神境界':'Break through to the Spirit Transformation realm.',
        '最寻常的疗伤丹，入口化暖流，瞬愈皮肉之伤，江湖修士人人随身。':'The most common healing pill, a warm flow mends flesh wounds at once, carried by every wanderer.',
        '续一线将断之命，重伤垂死服之可回元气，救急的保命灵丹。':'Extends a fading life, restores vitality from near death, an emergency life-saving pill.',
        '九转火候炼成的还魂奇药，魂飞魄散前一线尚存便可拉回人间。':'A soul-return miracle refined in nine turns, pulling back one with a thread of soul left.',
        '散末状的聚灵药，化水饮下灵海顿涌，是斗法前常备的回灵之物。':'A powder that gathers spirit, drunk in water it floods the spirit sea, a common pre-battle refill.',
        '凝水成丹的灵液，一口下去灵力沛然，久战不竭之倚仗。':'A liquid condensed into pill, one sip brims spirit power, a stay in long fights.',
        '太乙仙池所淬的神液，饮之灵海暴涨，乃高阶修士的续灵至宝。':'Divine liquid quenched in the Taiyi immortal pool, it swells the spirit sea, a high-level refill treasure.',
        '引虚气入丹田的悟道丹，服之战力自长，省去数年苦修。':'A dao pill drawing void qi into the core, it grows battle power, saving years of hard training.',
        '蕴大道碎片的丹丸，服下如亲聆先贤讲法，战力与悟性同进。':'A pill holding great-dao fragments, like hearing sages teach, raising power and wisdom.',
        '专破境界壁障的散剂，战力将满时服之，可省去闭关磨剑之苦。':'A powder that breaks realm walls, taken near full power, sparing closed-door grinding.',
        '激发凶性的战丹，三回合内攻伐暴涨，以命换命的拼命之选。':'A battle pill that awakens ferocity, attack surges for 3 turns, a life-for-life gamble.',
        '裂天之威凝于丹，三回合攻伐如雷霆裂空，越阶搏杀的奇兵。':'Sky-splitting might in a pill, attack cracks like thunder for 3 turns, a surprise against higher foes.',
        '借玄龟之壳的守丹，三回合内防御坚若磐石，硬抗强敌必备。':'A guard pill from the mystery turtle shell, defense hard as rock for 3 turns, a must against strong foes.',
        '镇岳之力凝丹，三回合如负山岳，任敌万击而不摇。':'Mountain-suppressing might in a pill, like bearing a mountain for 3 turns, unmoved by myriad hits.',
        '通玄之丹开慧眼，下次突破时壁障自松，成功率小增。':'A mystery-opening pill opens the wise eye, next breakthrough eases and its rate slightly rises.',
        '比破障丹更进一步的灵丹，几乎洞穿境界之膜，破境十拿九稳。':'A step beyond the barrier pill, nearly piercing the realm veil, breakthrough almost assured.',
        '温玉之精炼的培元丹，常服可令肌骨如玉，气血永久小增。':'A vitality pill refined from warm jade, long use makes flesh jade-like, health slightly rises forever.',
        '嗅之生机盎然的不死奇丹，根骨重塑，气血永久大涨。':'A deathless wonder pill full of vitality, rebuilds bones, health rises greatly forever.',
        '裂石之劲凝丹，筋骨生力，攻击永久小增，夯实根基。':'Stone-splitting force in a pill, sinews gain strength, attack slightly rises forever.',
        '霸王扛鼎之力的丹丸，服之如披甲胄，攻击永久猛进。':'A pill of overlord strength, like wearing armor, attack rises sharply forever.',
        '戮天凶威炼成的丹，杀伐之气刻入道躯，攻击永久剧增。':'A pill of heaven-slaying might, killing qi etched in the dao body, attack rises hugely forever.',
        '拓灵海如拓湖泊的丹药，神识容量永久大增，术法更绵长。':'A pill that widens the spirit sea like a lake, spirit sense capacity rises forever, spells last longer.',
        '炼神识如炼金丹的奇药，灵台永阔，是高阶术修的基石。':'A wonder that refines spirit sense like a golden pill, the mind stays vast, base of high spellcasters.',
        '玄龟甲气凝丹，皮膜生甲，防御永久小增，立于不败。':'Mystery turtle shell qi in a pill, skin grows armor, defense slightly rises forever.',
        '山岳之重入体的丹，筋骨如铸，防御永久猛进。':'Mountain weight enters the body, sinews like cast iron, defense rises sharply forever.',
        '破军星力凝丹，出手必中要害，暴击率永久小增。':'Army-breaker star power in a pill, hits vital points, crit rate slightly rises forever.',
        '锐锋之意刻入神魂，剑出必见血，暴击率永久大涨。':'Sharp-edge will etched in the soul, the blade draws blood, crit rate rises greatly forever.',
        '疾风之意凝丹，身法如电，速度永久小增，先发制人。':'Swift-wind will in a pill, movement like lightning, speed slightly rises forever, strike first.',
        '流光绕身之丹，动静皆先人一步，速度永久猛进。':'A pill of flowing light around the body, always a step ahead, speed rises sharply forever.',
        '混元一气炼成的金丹，攻防气血灵力同铸，根基永久全方大涨。':'A golden pill of primordial qi, forging attack, defense, health and spirit together, all foundations rise forever.',
        '聚宝气于丹的奇物，服之财源广进——立得一笔灵石傍身。':'A wonder concentrating fortune qi, wealth flows after taking it, gaining a sum of spirit stones at once.',
        '剑身青芒流转，寻常铁匠亦可锻出的入门飞剑，轻灵顺手。':'Green light flows on the blade, an entry flying sword any smith can forge, light and handy.',
        '剑势如流云舒卷，轻柔中藏杀机，初入筑基者爱用。':'Sword momentum like drifting clouds hides killing intent, loved by new Foundation cultivators.',
        '刀光如月轮斩落，重劈之威惊蛮，金丹修士的趁手兵刃。':'Blade light falls like a moon wheel, its heavy cleave awes, a Golden Core handy weapon.',
        '枪出裂虚空，洞穿之劲无匹，挑刺之间敌胆已寒。':'The spear cracks the void, its piercing force unmatched, foes tremble mid-thrust.',
        '戟尖焚天烈焰缠绕，一挥如燎原，元婴修士的凶兵。':'Burning-sky flame wraps the halberd tip, one swing like wildfire, a Nascent Soul fierce weapon.',
        '锤落惊雷炸响，重击碎骨裂金，硬碰硬的霸道之器。':'The hammer falls with thunder, heavy blows shatter bone and gold, an overbearing blunt tool.',
        '太虚之气凝成的飞环，环转间空间扭曲，大能方驭之。':'A flying ring of great-void qi, warps space as it turns, wielded only by mighty ones.',
        '专诛神魂的凶枪，一刺直没灵台，乃诛神灭仙之兵。':'A fierce spear that slays souls, one thrust sinks to the mind, a god-immortal killer.',
        '取玄龟甲片缀成的护甲，笨重却耐打，新手的第一层壳。':'Armor of mystery turtle plates, clumsy but tough, a newbie first shell.',
        '轻若流云的道袍，御风而行不滞，兼守与逸。':'A dao robe light as drifting cloud, rides wind without drag, both guard and ease.',
        '铠上刻镇魂纹，近身邪祟自退，金丹护身的铁壁。':'Armor carved with soul-suppressing runes, nearby evil retreats, a Golden Core iron wall.',
        '以陨星铁铸的战甲，星力流转护体，元婴不破之屏障。':'Battle armor of fallen-star iron, star power guards the body, a Nascent Soul unbreakable barrier.',
        '太乙道纹织就的道衣，法术加身更利，术修至爱。':'A dao garment of Taiyi runes, spells land better, beloved by casters.',
        '混元一气裹身的神甲，万法难侵，大能亦是法宝。':'A divine armor wrapped in primordial qi, all arts hardly pierce, itself a mighty treasure.',
        '明王法相镇于甲，岿然不动，受万击而身不摇。':'Wisdom king form sits on the armor, immovable, unshaken by myriad blows.',
        '千环相扣的锁子甲，周天灵气自循，守得密不透风。':'Chainmail of a thousand linked rings, heavenly cycle qi self-circulates, airtight defense.',
        '翠玉琢成的腰环，温润养神，初修道人的小饰。':'A waist ring carved of jade green, gently nourishes spirit, a novice small trinket.',
        '铃响引疾风绕身，身法陡快，先发制人。':'The bell rings and swift wind wraps the body, movement quickens, strike first.',
        '玉中封镇魂符，邪念难侵、灵台长清，金丹修士的护身符。':'A jade sealing a soul-suppressing talisman, evil thoughts hardly enter, a Golden Core guard charm.',
        '链缀星辰碎屑，运势加身、出手更利，元婴之饰。':'A chain of star fragments, fortune and sharper strikes, a Nascent Soul ornament.',
        '太虚之气凝于戒，戴之如纳一方小乾坤，大能标配。':'Great-void qi condensed in the ring, wearing holds a small world, a mighty standard.',
        '环中藏因果线，牵敌命脉，出手必中要害。':'The ring hides karma threads, pulls the foe life line, strikes vital points.',
        '铃音含混沌意，闻之识海翻腾，扰敌心神。':'Bell sound holds chaos meaning, the mind sea churns on hearing, disturbing foes.',
        '珠映天命轨迹，趋吉避凶、运势长隆，元婴至宝。':'The pearl mirrors heaven mandate, seeks good and avoids ill, fortune ever high, a Nascent Soul treasure.',
        '七层塔影镇压万物，邪祟入内即被磨灭，万法归一的镇派之宝。':'Seven tower shadows suppress all, evil entering is erased, the sect-suppressing treasure of unified arts.',
        '镜分阴阳，照敌则反照其伤，以彼之矛攻彼之盾。':'The mirror splits yin-yang, shines foes to reflect their wounds, using their spear on their shield.',
        '锤重如山岳倾压，一击镇敌于地，擅以力破巧。':'The hammer weighs like a falling mountain, one blow pins foes, breaks skill with force.',
        '灯火护心，危时替主挡下一击，入门修士的保命灯。':'Lamp light guards the heart, blocks one blow in danger, a novice life-saving lamp.',
        '图卷展开便纳山河，困敌于一方天地，演绎造化之威。':'The scroll unfolds to hold mountains and rivers, traps foes in a world, showing creation might.',
        '轮转两仪生四象，反弹伤害、化守为攻，玄妙非常。':'The wheel turns two-forms into four-images, reflects damage and turns guard to attack, very profound.',
        '针落如定沧海，镇压一切波澜，守势无双。':'The needle falls like calming the sea, suppresses all waves, unmatched defense.',
        '环鸣九霄，危急时护主挡击，轻盈易驭的护身环。':'The ring chimes to nine heavens, guards the master in danger, a light easy guard ring.',
        '太清仙宗镇派之宝塔，塔影垂落便镇万法，大乘以上方能请回。':'The Supreme Purity sect-suppressing pagoda, its shadow suppresses all arts, returnable only above Mahayana.',
        '古战场夺来的诸天炼器鼎，鼎气压塌虚空，真仙以上方可驭使。':'An all-heavens forging cauldron taken from an ancient battlefield, its weight collapses the void, wielded above True Immortal.',
        '映照诸天平衡的无衡古镜，照敌则反照其伤，金仙以上方承其力。':'An ancient balance mirror reflecting all-heaven balance, shines foes to reflect their wounds, borne above Gold Immortal.',
        '九转周天的基础功法，气脉流转略快，新晋修士可习。':'A basic nine-turn cycle method, qi flows a bit faster, for new cultivators.',
        '纳太阴虚冥之气，修炼时如临幽潭，效率大进。':'Draws Taiyin nether qi, cultivation like a dark pool, efficiency greatly rises.',
        '演两仪生灭之机，吐纳间微尘化乾坤，金丹以上方窥门径。':'Plays the two-forms birth-death mechanism, breath turns dust to cosmos, glimpsed above Golden Core.',
        '引周天星辰之力入体，修炼如沐星河，元婴大修方成。':'Draws heavenly cycle star power into the body, cultivation bathes in star rivers, a Nascent Soul great work.',
        '采鸿蒙未判之紫气，道韵自生，化神以上方可承之。':'Gathers Hongmeng unjudged purple qi, dao rhythm self-arises, borne above Spirit Transformation.',
        '混元无极、周流不息，乃近乎大道的吐纳至法，非大能不可驭。':'Primordial infinite, ever flowing, near-great-dao breathing, only mighty ones can wield.',
        '太清仙宗根本功法，紫极之气周转，修炼速率大增，大乘以上方窥门径。':'The Supreme Purity root method, purple-pole qi circulates, cultivation rate greatly rises, glimpsed above Mahayana.',
        '引紫霄神雷入丹田，吐纳间道韵自生，真仙大修方能承之。':'Draws purple-heaven divine thunder into the core, dao rhythm self-arises in breath, borne by True Immortal greats.',
        '离火真炎炼形神，修炼如浴火重生，金仙以上方可驭使。':'Li-fire true flame refines body and spirit, cultivation like rebirth in fire, wielded above Gold Immortal.',
        '玄天之力镇万魔，一呼一吸皆是大神通，太乙天尊之传承。':'Mysterious heaven power suppresses myriad demons, each breath a great miracle, Taiyi Heavenly Venerate inheritance.',
        '浩然正气贯长虹，修炼速率夺天地造化，大罗金仙方成大器。':'Righteous qi pierces the rainbow, cultivation rate seizes heaven-earth creation, a Daluo Gold Immortal great vessel.',
        '大道无上之总纲，吐纳即与道同频，道祖方窥其万一。':'The supreme great-dao outline, breath tunes with the dao, glimpsed only by Dao Ancestors.',
        '通体燃火云的小犬，性烈忠诚，扑咬间带三分炎威。':'A small dog ablaze with fire clouds, fierce and loyal, bites carry three parts flame might.',
        '月宫玉兔，温顺而善护主，危时化盾挡灾。':'A moon-palace jade rabbit, gentle and protective, becomes a shield in danger.',
        '金翅雕，凌空喷吐烈焰，俯冲如雷，群攻好手。':'A gold-wing eagle, spits flame in air, dives like thunder, good at area attack.',
        '背负山河的玄龟，防御无双，护主如山不动。':'A mystery turtle bearing mountains and rivers, unmatched defense, guards like an unmoving mountain.',
        '四蹄踏火的灵马，冲撞带焰，疾如风、猛如虎。':'A spirit horse with burning hooves, charges aflame, swift as wind and fierce as tiger.',
        '通体墨玉的麒麟，一声长吟震散敌防，瑞兽之威。':'An ink-jade qilin, one cry shatters foe defense, the might of an auspicious beast.',
        '通万物之白的白泽，悬角辟邪，护主万邪难近。':'A Baize knowing all things, its horn wards evil, protecting the master from all ill.',
        '浴火重生的朱雀，火羽焚天，群攻之极致。':'A Vermilion Bird reborn in fire, flame feathers burn the sky, the peak of area attack.',
        '传说中龙族始祖的一缕血脉，龙吟镇万灵，至强灵宠。':'A blood thread of the dragon clan progenitor, dragon roar quiets all spirits, the strongest pet.',
        '统御瑞兽一脉的麒麟王，一声长吟震碎敌防，大乘修士的护道至尊。':'The qilin king ruling auspicious beasts, one cry shatters foe defense, a Mahayana guardian sovereign.',
        '通晓万物之白的白泽之王，悬角辟尽诸邪，真仙方可收为护法。':'The Baize king knowing all things, its horn wards all evil, a True Immortal guardian.',
        '焚天重生的朱雀女皇，火羽燎原、群攻无双，金仙座下圣禽。':'The Vermilion Bird empress reborn in fire, flame feathers scorch plains, unmatched area attack, a Gold Immortal sacred bird.',
        '龙族太初始祖的本源血脉，龙吟镇万灵、吐息溺星河，太乙天尊方能驭使。':'The primordial progenitor dragon source blood, roar quiets all spirits and breath drowns star rivers, wielded by Taiyi Heavenly Venerate.',
        '攻击 +4%/级':'Attack +4% per level.',
        '暴击率 +2%/级':'Crit rate +2% per level.',
        '防御 +5%/级':'Defense +5% per level.',
        '气血 +4%/级':'Health +4% per level.',
        '灵力 +5%/级':'Spirit +5% per level.',
        '速度 +4%/级':'Speed +4% per level.',
        '修炼速率 +4%/级':'Cultivation rate +4% per level.',
        '灵石获取 +5%/级':'Spirit stone gain +5% per level.',
        '出战灵宠属性 +6%/级':'Active pet stats +6% per level.',
        '突破成功率 +3%/级':'Breakthrough rate +3% per level.',
        '渡劫成功率 +4%/级':'Tribulation rate +4% per level.',
        '斗法伤害 +4%/级':'Combat damage +4% per level.',
        '受到伤害 -3%/级':'Damage taken -3% per level.',
        '喂养灵宠的灵粮，可助其增长战力':'Spirit beast feed that helps pets grow battle power.',
        '灵宠化形进阶之丹，等级足时可令其蜕变':'A pill for pet form-change, triggers evolution at enough level.',
        '产出灵石/秒':'Produces spirit stones per second.',
        '产出悟性/小时':'Produces comprehension per hour.',
        '产出悟性经验/小时':'Produces comprehension exp per hour.'
    }
};

/* 当前语言：zh / en（优先 localStorage，其次存档 settings.lang） */
let CUR_LANG = (typeof localStorage !== 'undefined' && localStorage.getItem('xiantu_lang')) || 'zh';

function getLang() { return CUR_LANG; }

/* UI 文案查表 */
function T(key, fallback) {
    if (CUR_LANG === 'en') {
        const v = I18N.en[key];
        if (v !== undefined) return v;
    }
    return (fallback !== undefined) ? fallback : key;
}

/* 数据名：传对象（含 .name）或纯字符串 */
function DN(obj) {
    let s = (obj && typeof obj === 'object') ? obj.name : obj;
    if (s == null) return '';
    if (CUR_LANG === 'en') { const v = I18N.DATA[s]; if (v !== undefined) return v; }
    return s;
}

/* 数据描述 */
function DD(obj) {
    let s = (obj && typeof obj === 'object') ? obj.desc : obj;
    if (s == null) return '';
    if (CUR_LANG === 'en') { const v = I18N.DATA_DESC && I18N.DATA_DESC[s]; if (v !== undefined) return v; }
    return s;
}

/* 仅按中文字串查译（用于已存为字符串的字段，如 ch.realmName / f.realmName） */
function TS(str) {
    if (!str) return str;
    if (CUR_LANG === 'en') { const v = I18N.DATA[str]; if (v !== undefined) return v; }
    return str;
}

/* 境界全名（含层位），随语言切换：中文「练气一层」/ 英文「Qi Refining Lv1」 */
function realmLabel(p) {
    if (!p) return '';
    const r = (typeof getRealm === 'function') ? getRealm(p.realmIdx) : null;
    if (!r) return '';
    const nm = DN(r);
    if (CUR_LANG === 'en') return nm + ' Lv' + p.realmLayer;
    const cn = (typeof cnNum === 'function') ? cnNum(p.realmLayer) : ('' + p.realmLayer);
    return nm + cn + '层';
}

/* 切换语言：写持久化 → 重渲染 UI */
function setLang(code) {
    if (code !== 'zh' && code !== 'en') code = 'zh';
    CUR_LANG = code;
    applyNameLocale();
    if (typeof localStorage !== 'undefined') { try { localStorage.setItem('xiantu_lang', code); } catch (e) {} }
    // 同步进存档
    try {
        if (typeof Game !== 'undefined' && Game.player && Game.player.settings) {
            Game.player.settings.lang = code;
            if (typeof Game.save === 'function') Game.save();
        }
    } catch (e) {}
    applyI18N();
    if (typeof UI !== 'undefined' && typeof UI.refreshAll === 'function') { try { UI.refreshAll(); } catch (e) {} }
    if (typeof document !== 'undefined') { try { document.dispatchEvent(new Event('langchange')); } catch (e) {} }
}

/* 把 [data-i18n]（textContent）/ [data-i18n-title]（title）/ [data-i18n-ph]（placeholder）
   按当前语言填充；首次运行缓存中文原值，切回中文时还原。 */
function applyI18N() {
    if (typeof document === 'undefined') return;
    document.querySelectorAll('[data-i18n]').forEach(el => {
        if (el.dataset.i18nZh === undefined) el.dataset.i18nZh = el.textContent;
        const key = el.dataset.i18n;
        el.textContent = (CUR_LANG === 'en') ? T(key, el.dataset.i18nZh) : el.dataset.i18nZh;
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        if (el.dataset.i18nTitleZh === undefined) el.dataset.i18nTitleZh = (el.getAttribute('title') || '');
        const key = el.dataset.i18nTitle;
        el.setAttribute('title', (CUR_LANG === 'en') ? T(key, el.dataset.i18nTitleZh) : el.dataset.i18nTitleZh);
    });
    document.querySelectorAll('[data-i18n-ph]').forEach(el => {
        if (el.dataset.i18nPhZh === undefined) el.dataset.i18nPhZh = (el.getAttribute('placeholder') || '');
        const key = el.dataset.i18nPh;
        el.setAttribute('placeholder', (CUR_LANG === 'en') ? T(key, el.dataset.i18nPhZh) : el.dataset.i18nPhZh);
    });
}

/* 数字本地化：英文模式用 K/M/B 等 SI 后缀，避免中文 万/亿 单位（config.js 的 fmtNum 不动，此处覆盖） */
if (typeof fmtNum === 'function') {
  var _fmtNumZH = fmtNum;
  fmtNum = function(n) {
    if (CUR_LANG === 'en') {
      var units = ['', 'K', 'M', 'B', 'T', 'Qa', 'Qi', 'Sx', 'Sp', 'Oc', 'No', 'Dc', 'UD', 'DD', 'TD'];
      var u = 0, x = n;
      while (Math.abs(x) >= 1000 && u < units.length - 1) { x /= 1000; u++; }
      return u === 0 ? Math.floor(n).toString() : x.toFixed(2) + units[u];
    }
    return _fmtNumZH(n);
  };
}

/* 随机名字英文化：覆盖 config.js 的 randomName（lang.js 在其后加载）。
   英文模式从英文名字池取，避免中文 云/风 等泄漏到角色名 / 道友名。 */
if (typeof randomName === 'function') {
  var _randomNameZH = randomName;
  var EN_NAME_PRE = ['Azure','Crimson','Jade','Mystic','Nether','Solar','Lunar','Storm','Frost','Ember','Void','Celestial','Verdant','Radiant','Silent','Iron','Golden','Veiled','Ancient','Eternal'];
  var EN_NAME_CORE = ['Cloud','Wind','Thunder','Rain','Snow','Frost','Moon','Star','Sea','Mountain','Forest','Spring','Mist','Dawn','Sky','River','Flame','Stone','Lotus','Dragon'];
  var EN_NAME_SUF = ['', ' the Wise', ' the Adept', ' Immortal', ' Seeker', ' Sage', ' Ascendant', ' Wanderer', ' of the Peak'];
  randomName = function() {
    if (CUR_LANG === 'en') {
      var r = Math.random;
      if (r() < 0.5) return EN_NAME_PRE[Math.floor(r() * EN_NAME_PRE.length)] + ' ' + EN_NAME_CORE[Math.floor(r() * EN_NAME_CORE.length)];
      return EN_NAME_CORE[Math.floor(r() * EN_NAME_CORE.length)] + ' ' + EN_NAME_CORE[Math.floor(r() * EN_NAME_CORE.length)] + EN_NAME_SUF[Math.floor(r() * EN_NAME_SUF.length)];
    }
    return _randomNameZH();
  };
}

/* 默认玩家名英文化：英文模式把 config.defaultPlayer.name 改为英文，
   保证新档 / 深拷贝不会残留「无名修士」。不改动 config.js 文件本体。 */
function applyNameLocale() {
  try {
    if (typeof GameConfig === 'undefined' || !GameConfig.defaultPlayer) return;
    GameConfig.defaultPlayer.name = (CUR_LANG === 'en') ? 'Nameless Cultivator' : '无名修士';
  } catch (e) {}
}
applyNameLocale();

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { I18N, getLang, setLang, T, DN, DD, TS, realmLabel, applyI18N };
}
